// frontend/src/features/crm/pages/leads/LeadDrawer.jsx
import React, { useState, useEffect } from "react";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/components/ui/drawer";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { CalendarIcon } from "lucide-react";
import { format } from "date-fns";


const stringComponent = [
  { value: "is", label: "Is" },
  { value: "is_not", label: "Is Not" },
  { value: "contains", label: "Contains" },
  { value: "does_not_contain", label: "Does Not Contain" },
  { value: "starts_with", label: "Starts With" },
  { value: "ends_with", label: "Ends With" },
];

const dateComponent = [
  { value: "is", label: "Is" },
  { value: "is_not", label: "Is Not" },
  { value: "before", label: "Before" },
  { value: "after", label: "After" },
  { value: "between", label: "Between" },
];

const numberComponent = [
  { value: "is", label: "Is" },
  { value: "is_not", label: "Is Not" },
  { value: "greater_than", label: "Greater Than" },
  { value: "less_than", label: "Less Than" },
  { value: "between", label: "Between" },
];

const insuranceLeadStatusOptions = ["New", "Contacted", "Qualified", "Proposal", "Negotiation", "Closed Won", "Closed Lost"];
const leadStatusStageOption = ["Lead", "Prospect", "Customer"];

const allFields = [
  { label: 'Created Time', model: 'createdTime', placeholder: 'Created Time', type: 'date' },
  { label: 'Layout', model: 'layout', placeholder: 'Layout', type: 'text' },
  { label: 'Insurance Lead Name All', model: 'insurenceLeadNameAll', placeholder: 'Lead Name', type: 'text' },
  { label: 'Insurance Lead Status', model: 'insuranceLeadStatus', placeholder: 'Status', type: 'array', options: insuranceLeadStatusOptions },
  { label: 'Lead Status Stage', model: 'leadStatusStage', placeholder: 'Stage', type: 'array', options: leadStatusStageOption },
  { label: 'Mobile', model: 'mobile', placeholder: 'Mobile', type: 'text' },
  { label: 'Insurance Lead Source', model: 'insuranceLeadSource', placeholder: 'Source', type: 'text' },
  { label: 'Assigned Advisor', model: 'assignedAdvisor', placeholder: 'Advisor', type: 'text' },
  { label: 'Email', model: 'email', placeholder: 'Email', type: 'email' },
  { label: 'Services Requested', model: 'servicesRequested', placeholder: 'Services', type: 'text' },
  { label: 'GCLID', model: 'gclid', placeholder: 'GCLID', type: 'text' },
  { label: 'First Page Visited', model: 'firstPageVisited', placeholder: 'Page URL', type: 'text' },
  { label: 'Ad Network', model: 'adNetwork', placeholder: 'Ad Network', type: 'text' },
  { label: 'Last Activity Time', model: 'lastActivityTime', placeholder: 'Last Activity', type: 'text' },
  { label: 'Total Interaction Time (mins)', model: 'totalInteractionTime', placeholder: 'Minutes', type: 'number' },
  { label: 'Phone', model: 'phone', placeholder: 'Phone', type: 'text' },
  { label: 'Created By', model: 'createdBy', placeholder: 'Creator', type: 'text' },
  { label: 'Ad Campaign Name', model: 'adCampaignName', placeholder: 'Campaign', type: 'text' },
  { label: 'Facebook Ad', model: 'facebookAd', placeholder: 'Facebook Ad', type: 'text' },
  { label: 'First Name', model: 'firstName', placeholder: 'First Name', type: 'text' },
  { label: 'Last Name All', model: 'lastNameAll', placeholder: 'Last Name', type: 'text' },
  { label: 'Keyword', model: 'keyword', placeholder: 'Keyword', type: 'text' },
  { label: 'Submit Page URL', model: 'submitPageUrl', placeholder: 'Submit URL', type: 'text' },
  { label: 'LP URL Data', model: 'lpUrlData', placeholder: 'LP URL', type: 'text' },
  { label: 'GCLID Data', model: 'gclidData', placeholder: 'GCLID Data', type: 'text' },
];

const LeadDrawer = ({ isOpen, onClose, onSearchResults }) => {
  const [searchFieldTitle, setSearchFieldTitle] = useState("");
  const [fieldChecks, setFieldChecks] = useState({});
  const [operationForm, setOperationForm] = useState({});
  const [form, setForm] = useState({});
  const [inputVisibility, setInputVisibility] = useState({});
  const [betweenFields, setBetweenFields] = useState({});
  const [datePickers, setDatePickers] = useState({});

  const getOperationOptions = (field) => {
    console.log(field.type);
    if (['text', 'email', 'picklist', 'array'].includes(field.type)) {
      return stringComponent;
    } else if (field.type === 'date') {

      return dateComponent;
    } else if (field.type === 'number') {
      return numberComponent;
    } else {
      return stringComponent;
    }
  };

  const handleOperationChange = (fieldName, operation) => {
    setBetweenFields(prev => ({ ...prev, [fieldName]: operation === "between" }));
    setInputVisibility(prev => ({ ...prev, [fieldName]: operation && operation !== "between" }));
  };

  const handleCheckboxChange = (model, checked) => {
    setFieldChecks(prev => ({ ...prev, [model]: checked }));
    if (checked) {
      const operations = getOperationOptions(allFields.find(f => f.model === model));
      setOperationForm(prev => ({ ...prev, [model]: operations[0]?.value || '' }));
    } else {
      setOperationForm(prev => ({ ...prev, [model]: '' }));
    }
  };

  const searchLeads = () => {
    const searchFields = [];
    allFields.forEach(field => {
      if (fieldChecks[field.model]) {
        let value = '';
        if (operationForm[field.model] === 'between') {
          const from = form[`${field.model}From`];
          const to = form[`${field.model}To`];
          if (from && to) {
            value = [from, to];
          }
        } else {
          value = form[field.model] || '';
        }
        searchFields.push({
          field: field.model,
          operation: operationForm[field.model] || 'is',
          value
        });
      }
    });
    onSearchResults(searchFields);
    onClose();
  };

  const resetFilters = () => {
    setForm({});
    setFieldChecks({});
    setOperationForm({});
    setInputVisibility({});
    setBetweenFields({});
  };

  const filteredFields = allFields.filter(field =>
    field.label.toLowerCase().includes(searchFieldTitle.toLowerCase())
  );

  return (
    <Drawer open={isOpen} onOpenChange={onClose} direction="right" >
      <DrawerContent width="22%">
        <DrawerHeader>
          <DrawerTitle>Filter Fields By</DrawerTitle>
          <DrawerDescription>Search and filter leads</DrawerDescription>
        </DrawerHeader>
        <div className="px-4">
          <Input
            placeholder="Search fields..."
            value={searchFieldTitle}
            onChange={(e) => setSearchFieldTitle(e.target.value)}
            className="mb-4"
          />
          <div className="space-y-2 max-h-[calc(100vh-200px)] overflow-y-auto">
            {filteredFields.map(field => (
              <div key={field.model} className="space-y-2">
                <div className="flex items-center space-x-2">
                  <Checkbox
                    id={field.model}
                    checked={fieldChecks[field.model] || false}
                    onCheckedChange={(checked) => handleCheckboxChange(field.model, checked)}
                  />
                  <Label htmlFor={field.model}>{field.label}</Label>
                </div>
                {fieldChecks[field.model] && (
                  <div className="ml-6 space-y-2">
                    <Select
                      value={operationForm[field.model] || ""}
                      onValueChange={(value) => {
                        setOperationForm(prev => ({ ...prev, [field.model]: value }));
                        handleOperationChange(field.model, value);
                      }}
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select operation" />
                      </SelectTrigger>
                      <SelectContent>
                        {getOperationOptions(field).map(option => (
                          <SelectItem key={option.value} value={option.value}>
                            {option.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {betweenFields[field.model] ? (
                      <div className="space-y-2">
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button
                              variant="outline"
                              className={`w-full justify-start text-left font-normal ${!form[`${field.model}From`] && "text-muted-foreground"}`}
                            >
                              <CalendarIcon className="mr-2 h-4 w-4" />
                              {form[`${field.model}From`] ? format(form[`${field.model}From`], "PPP") : "Pick from date"}
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <Calendar
                              mode="single"
                              selected={form[`${field.model}From`]}
                              onSelect={(date) => setForm(prev => ({ ...prev, [`${field.model}From`]: date }))}
                              initialFocus
                            />
                          </PopoverContent>
                        </Popover>
                        <Popover>
                          <PopoverTrigger asChild>
                            <Button
                              variant="outline"
                              className={`w-full justify-start text-left font-normal ${!form[`${field.model}To`] && "text-muted-foreground"}`}
                            >
                              <CalendarIcon className="mr-2 h-4 w-4" />
                              {form[`${field.model}To`] ? format(form[`${field.model}To`], "PPP") : "Pick to date"}
                            </Button>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <Calendar
                              mode="single"
                              selected={form[`${field.model}To`]}
                              onSelect={(date) => setForm(prev => ({ ...prev, [`${field.model}To`]: date }))}
                              initialFocus
                            />
                          </PopoverContent>
                        </Popover>
                      </div>
                    ) : (field.type === 'array' || field.type === 'picklist') ? (
                      <Select
                        value={form[field.model] || ""}
                        onValueChange={(value) => setForm(prev => ({ ...prev, [field.model]: value }))}
                      >
                        <SelectTrigger className="w-full">
                          <SelectValue placeholder="Select value" />
                        </SelectTrigger>
                        <SelectContent>
                          {field.options?.map(option => (
                            <SelectItem key={option} value={option}>
                              {option}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    ) : field.type === 'date' ? (
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            variant="outline"
                            className={`w-full justify-start text-left font-normal ${!form[field.model] && "text-muted-foreground"}`}
                          >
                            <CalendarIcon className="mr-2 h-4 w-4" />
                            {form[field.model] ? format(form[field.model], "PPP") : "Pick a date"}
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0">
                          <Calendar
                            mode="single"
                            selected={form[field.model]}
                            onSelect={(date) => setForm(prev => ({ ...prev, [field.model]: date }))}
                            initialFocus
                          />
                        </PopoverContent>
                      </Popover>
                    ) : (
                      <Input
                        type={field.type}
                        placeholder={field.placeholder}
                        value={form[field.model] || ""}
                        onChange={(e) => setForm(prev => ({ ...prev, [field.model]: e.target.value }))}
                        className="w-full"
                      />
                    )}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
        <DrawerFooter>
          <div className="flex gap-2 justify-center">
            <Button className="text-white" variant="primary" onClick={searchLeads}>
              Search
            </Button>
            <Button variant="destructive" onClick={resetFilters}>
              Reset
            </Button>
          </div>
        </DrawerFooter>
      </DrawerContent>
    </Drawer >
  );
};

export default LeadDrawer;

// client/app/src/views/leads/LeadDrawer.vue
<template>
  <div class="drawer-main-div card">
    <div class="drawer" :class="{ 'is-open': isOpen, 'is-visible': isVisible }">
      <div class="drawer__overlay" :style="{ transitionDuration: `${speed}ms` }"></div>
      <div class="drawer__content" v-click-away="closeDrawer" :style="{
        maxWidth: maxWidth,
        transitionDuration: `${speed}ms`,
        backgroundColor: backgroundColor,
      }">
        <div class="px-3 py-1">
          <i @click="closeDrawer" class="fa fa-arrow-right cursor-pointer"></i>
        </div>
        <p class="font-normal mb-2 mx-3">Filter Fields By</p>
        <input v-model="searchFieldTitle" class="form-control mb-2 mx-3" onclick="focusSearchField((e)=>searchFieldTitle = e.target.value)" placeholder="Search fields..." />
        <div> {{  }}</div>
        <!-- Drawer Body -->
        <div class="message-details d-flex flex-column" style="height: 100%;">
          <div style="overflow-y: auto; max-height: calc(100vh - 160px);" class="px-3 pt-0">

            <div v-for="field in filterdFields" :key="field.model" class="form-group mb-0">
              <div class="d-flex align-items-center gap-2 mb-0">

                <!-- <input class="form-check-input my-auto" type="checkbox" v-model="fieldChecks[field.model]" /> -->
                <input type="checkbox" class="form-check-input"  style="width: 1rem; height: 1rem;" v-model="fieldChecks[field.model]" @change="() => {
                  if (fieldChecks[field.model]) {
                    const operations = getOperationOptions(field);
                    operationForm[field.model] = operations[0]?.value || '';
                  } else {
                    operationForm[field.model] = '';
                  }
                }" />
                <label class="mt-2">{{ field.label }}</label>
              </div>



              <div v-if="fieldChecks[field.model]" class="mt-0">


                <select v-model="operationForm[field.model]" class="form-select mb-1"
                  @change="handleOperationChange(field.model, $event.target.value)">
                  <option v-for="option in getOperationOptions(field)" :key="option.value" :value="option.value">
                    {{ option.label }}
                  </option>
                </select>


                <!-- First Priority: BETWEEN Selected => 2 fields -->
                <div v-if="betweenFields[field.model]" class="d-flex flex-column gap-2">
                  <input type="datetime-local" class="form-control" v-model="form[`${field.model}From`]"
                    placeholder="From" />
                  <input type="datetime-local" class="form-control" v-model="form[`${field.model}To`]"
                    placeholder="To" />
                </div>

                <!-- PICKLIST or ARRAY input -->
                <select
                  v-else-if="(field.type === 'array' || field.type === 'picklist') && (fieldChecks[field.model] || inputVisibility[field.model])"
                  v-model="form[field.model]" class="form-select">
                  <option v-for="option in field.options || []" :key="option" :value="option">
                    {{ option }}
                  </option>
                </select>

                <!-- Otherwise: Single input if Checkbox ticked OR Operation selected -->
                <input v-else-if="fieldChecks[field.model] || inputVisibility[field.model]"
                  :type="field.type === 'date' ? 'datetime-local' : field.type" class="form-control"
                  v-model="form[field.model]" :placeholder="field.placeholder" />

              </div>
            </div>

          </div>

          <!-- Footer Buttons -->
          <div class="d-flex justify-content-center gap-2 border-top bg-white"
            style="position: sticky; bottom: 0; padding: 1rem; z-index: 2;">
            <button class="btn btn-info " @click="searchLeads">Search</button>
            <button class="btn btn-danger" @click="resetFilters">Reset</button>
          </div>

        </div>

        <slot></slot>
      </div>
    </div>
  </div>
</template>




<script>
import { directive } from "vue3-click-away";
import { stringComponent, dateComponent, numberComponent } from "../../contants/searchPickList";
import { insuranceLeadStatusOptions, leadStatusStageOption } from "./utils/picklist"
import data from "../referrals/utils/data";
export default
  {

    name: "Drawer",


    directives: {
      ClickAway: directive,
    },

    props: {
      updateData: {
        type: Function,
      },
      updateNotes: {
        type: Function,
      },
      addNotes: {
        type: Function,
      },
      selectedButton: {
        type: String
      },
      isOpen: {
        type: Boolean,
        required: false,
        default: false,
      },
      maxWidth: {
        type: String,
        required: false,
        default: "400px",
      },
      // Transition Speed in Milliseconds
      speed: {
        type: Number,
        required: false,
        default: 300,
      },
      backgroundColor: {
        type: String,
        required: false,
        default: "#fafafa",
      },
    },

    data() {
      return {
        form: {
          createdTime: '',
          layout: '',
          insurenceLeadNameAll: '',
          insuranceLeadStatus: '',
          leadStatusStage: '',
          mobile: '',
          insuranceLeadSource: '',
          assignedAdvisor: '',
          email: '',
          servicesRequested: '',
          gclid: '',
          firstPageVisited: '',
          adNetwork: '',
          lastActivityTime: '',
          totalInteractionTime: '',
          phone: '',
          createdBy: '',
          adCampaignName: '',
          facebookAd: '',
          firstName: '',
          lastNameAll: '',
          keyword: '',
          submitPageUrl: '',
          lpUrlData: '',
          gclidData: '',
        },

        fieldChecks: {
          createdTime: false,
          layout: false,
          insurenceLeadNameAll: false,
          insuranceLeadStatus: false,
          leadStatusStage: false,
          mobile: false,
          insuranceLeadSource: false,
          assignedAdvisor: false,
          email: false,
          servicesRequested: false,
          gclid: false,
          firstPageVisited: false,
          adNetwork: false,
          lastActivityTime: false,
          totalInteractionTime: false,
          phone: false,
          createdBy: false,
          adCampaignName: false,
          facebookAd: false,
          firstName: false,
          lastNameAll: false,
          keyword: false,
          submitPageUrl: false,
          lpUrlData: false,
          gclidData: false,
        },
        operationForm: {
          createdTime: '',
          layout: '',
          insurenceLeadNameAll: '',
          insuranceLeadStatus: '',
          leadStatusStage: '',
          mobile: '',
          insuranceLeadSource: '',
          assignedAdvisor: '',
          email: '',
          servicesRequested: '',
          gclid: '',
          firstPageVisited: '',
          adNetwork: '',
          lastActivityTime: '',
          totalInteractionTime: '',
          phone: '',
          createdBy: '',
          adCampaignName: '',
          facebookAd: '',
          firstName: '',
          lastNameAll: '',
          keyword: '',
          submitPageUrl: '',
          lpUrlData: '',
          gclidData: '',
        },

        allFields: [
          { label: 'Created Time', model: 'createdTime', placeholder: 'Created Time', type: 'date' },
          { label: 'Layout', model: 'layout', placeholder: 'Layout', type: 'text' },
          { label: 'Insurance Lead Name All', model: 'insurenceLeadNameAll', placeholder: 'Lead Name', type: 'text' },
          { label: 'Insurance Lead Status', model: 'insuranceLeadStatus', placeholder: 'Status', type: 'array', options: insuranceLeadStatusOptions },
          {
            label: 'Lead Status Stage',
            model: 'leadStatusStage',
            placeholder: 'Stage',
            type: 'array',
            options: leadStatusStageOption,
          },

          { label: 'Mobile', model: 'mobile', placeholder: 'Mobile', type: 'text' },
          { label: 'Insurance Lead Source', model: 'insuranceLeadSource', placeholder: 'Source', type: 'text' },
          { label: 'Assigned Advisor', model: 'assignedAdvisor', placeholder: 'Advisor', type: 'text' },
          { label: 'Email', model: 'email', placeholder: 'Email', type: 'email' },
          { label: 'Services Requested', model: 'servicesRequested', placeholder: 'Services', type: 'text' },
          { label: 'GCLID', model: 'gclid', placeholder: 'GCLID', type: 'text' },
          { label: 'First Page Visited', model: 'firstPageVisited', placeholder: 'Page URL', type: 'text' },
          { label: 'Ad Network', model: 'adNetwork', placeholder: 'Ad Network', type: 'text' },
          { label: 'Last Activity Time', model: 'lastActivityTime', placeholder: 'Last Activity', type: 'text' },
          { label: 'Total Interaction Time (mins)', model: 'totalInteractionTime', placeholder: 'Minutes', type: 'number' },
          { label: 'Phone', model: 'phone', placeholder: 'Phone', type: 'text' },
          { label: 'Created By', model: 'createdBy', placeholder: 'Creator', type: 'text' },
          { label: 'Ad Campaign Name', model: 'adCampaignName', placeholder: 'Campaign', type: 'text' },
          { label: 'Facebook Ad', model: 'facebookAd', placeholder: 'Facebook Ad', type: 'text' },
          { label: 'First Name', model: 'firstName', placeholder: 'First Name', type: 'text' },
          { label: 'Last Name All', model: 'lastNameAll', placeholder: 'Last Name', type: 'text' },
          { label: 'Keyword', model: 'keyword', placeholder: 'Keyword', type: 'text' },
          { label: 'Submit Page URL', model: 'submitPageUrl', placeholder: 'Submit URL', type: 'text' },
          { label: 'LP URL Data', model: 'lpUrlData', placeholder: 'LP URL', type: 'text' },
          { label: 'GCLID Data', model: 'gclidData', placeholder: 'GCLID Data', type: 'text' },
        ],
        inputVisibility: {},
        betweenFields: {},
        searchFieldTitle: '',


        labelStyle: {
          border: '2px dashed lightgrey',
          borderRadius: '10px',
          width: '100%',
          height: '100px',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center'
        },
        contentStyle: {
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center'
        },
        iconStyle: {
          fontSize: '24px',
          marginBottom: '5px'
        },
        isVisible: false,
        isTransitioning: false,
        note: {
          noteTitle: '',
          noteText: ''
        }
      };
    },

    watch: {
      isOpen(val) {
        this.isTransitioning = true;
        if (val) {
          this.toggleBackgroundScrolling(true);
          this.isVisible = true;
        } else {
          this.toggleBackgroundScrolling(false);
          setTimeout(() => (this.isVisible = false), this.speed);
        }
        setTimeout(() => (this.isTransitioning = false), this.speed);
      },
      updateData(value) {
        if (value !== null) {
          this.note.noteText = value.description;
          this.note.noteTitle = value.title;
          this.note.id = value.id
        }
      }
    },

    methods: {
      getOperationOptions(field) {
        if (['text', 'email', 'picklist', 'array'].includes(field.type)) {
          return stringComponent;
        } else if (field.type === 'date') {
          return dateComponent;
        } else if (field.type === 'number') {
          return numberComponent;
        } else {
          return stringComponent;
        }
      },

      async searchLeads() {
        try {
          const searchFields = [];

          for (const field of this.allFields) {
            if (this.fieldChecks[field.model]) {  // checkbox checked

              let value = '';

              if (this.operationForm[field.model] === 'between') {
                const from = this.form[`${field.model}From`];
                const to = this.form[`${field.model}To`];

                console.log('Between From:', from);
                console.log('Between To:', to);

                if (from && to) {
                  const formattedFrom = from.replace('T', ' ') + ':00:000';
                  const formattedTo = to.replace('T', ' ') + ':00:000';

                  value = [formattedFrom, formattedTo];
                } else {
                  console.warn('Between selected but from/to is missing!');
                }
              } else {
                value = this.form[field.model] || '';
              }

              searchFields.push({
                field: field.model,
                operation: this.operationForm[field.model] || 'is',
                value: value
              });
            }
          }

          // console.log(' Final Payload:', searchFields);

         

          this.$emit('search-results', searchFields);

        } catch (error) {
          console.error('Error while searching leads:', error);
        }
      },

      resetFilters() {
        //  fields reset
        for (const key in this.form) {
          this.form[key] = '';
          this.form[key + 'From'] = '';
          this.form[key + 'To'] = '';
        }

        // checkboxes reset
        for (const key in this.fieldChecks) {
          this.fieldChecks[key] = false;
        }

        // operation select reset
        for (const key in this.operationForm) {
          this.operationForm[key] = '';
        }

        // input field visibility reset
        this.inputVisibility = {};
        this.betweenFields = {};
      },




      handleOperationChange(fieldName, operation) {
        // Reset dono visibility flags
        this.betweenFields[fieldName] = false;
        this.inputVisibility[fieldName] = false;

        if (operation === "between") {
          this.betweenFields[fieldName] = true;
        } else if (operation) {
          this.inputVisibility[fieldName] = true;
        }
      },




      resetNote() {
        this.note.noteText = "",
          this.note.noteTitle = ""
      },
      async handleSave() {
        try {
          const res = await this.addNotes(this.note);
          if (res.data.success) {
            this.note.noteTitle = '';
            this.note.noteText = '';
          }
        } catch (error) {
          console.error('Error saving note:', error);
        }
      },
      async handleUpdateNote() {
        try {
          const res = await this.updateNotes(this.note);
          console.log({ res })
          if (res.data.success) {
            this.note.noteTitle = '';
            this.note.noteText = '';
            this.closeDrawer();
          }
        } catch (error) {
          console.error('Error updating note:', error);
        }
      },
      isDescriptionValid() {
        return this.note.noteText.length <= 300;
      },
      isTitleValid() {
        return this.note.noteTitle.length <= 50;
      },
      toggleBackgroundScrolling(enable) {
        const body = document.querySelector("body");
        body.style.overflow = enable ? "hidden" : null;
        if (this.selectedButton !== "Update") {
          this.note.noteTitle = '';
          this.note.noteText = '';
        }

      },
      closeDrawer() {
        console.log("closeDrawer");
        if (!this.isTransitioning) {
          this.$emit("close");
        }
      },
    },

    mounted() {
      this.isVisible = this.isOpen;
    },

    computed: {
      filterdFields() {
        if (!this.searchFieldTitle) return this.allFields
        return this.allFields.filter(field => field.label.toLowerCase().includes(this.searchFieldTitle.toLowerCase()))
      }
    }
  };
</script>

<style lang="scss" scoped>
.drawer {
  visibility: hidden;

  &.is-visible {
    visibility: visible;
  }

  &.is-open {
    .drawer__overlay {
      opacity: 0.5;
    }

    .drawer__content {
      max-width: 24rem !important;
      transform: translateX(0);
    }
  }

  &__overlay {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    z-index: 200;
    opacity: 0;
    transition-property: opacity;
    background-color: #000000;
    user-select: none;
  }

  &__content {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    height: 100%;
    width: 100%;
    z-index: 9999;
    overflow: auto;
    transition-property: transform;
    display: flex;
    flex-direction: column;
    transform: translateX(100%);
    box-shadow: 0 2px 6px #777;
  }
}

.drawer-main-div {
  background-color: #fff;
}
</style>
