// frontend/src/features/Policy/investment/components/AnnuitantInfo.jsx
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import PhoneInput from 'react-phone-number-input';
import 'react-phone-number-input/style.css';
import Flatpickr from "react-flatpickr";
import "flatpickr/dist/themes/material_blue.css";
import {
  clientFirstPolicyOptions,
  typeOptions,
  genderOptions,
} from "@/utils/picklist";

const AnnuitantInfo = ({ formData, setFormData, onNext, onPrev }) => {
  const [investmentBasketData, setInvestmentBasketData] = useState(formData.InvestmentBasketData || []);

  const handleChange = (field, value) => {
    setFormData({ ...formData, [field]: value });
  };

  const handleNext = () => {
    setFormData({ ...formData, InvestmentBasketData: investmentBasketData });
    onNext();
  };

  const handlePrev = () => {
    onPrev();
  };

  const datePickerConfig = {
    dateFormat: "d/m/Y",
    allowInput: true,
  };

  const addRow = () => {
    setInvestmentBasketData([...investmentBasketData, {
      basketDate: '',
      type: '',
      fundCode: '',
      invPercentage: '',
      contribution: '',
    }]);
  };

  const deleteRow = (index) => {
    const newData = investmentBasketData.filter((_, i) => i !== index);
    setInvestmentBasketData(newData);
  };

  const updateBasket = (index, field, value) => {
    const newData = [...investmentBasketData];
    newData[index][field] = value;
    setInvestmentBasketData(newData);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Investment Basket</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>#</TableHead>
                  <TableHead>Action</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Fund Code</TableHead>
                  <TableHead>%</TableHead>
                  <TableHead>Contribution</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {investmentBasketData.map((item, index) => (
                  <TableRow key={index}>
                    <TableCell>{index + 1}</TableCell>
                    <TableCell>
                      <Button
                        variant="destructive"
                        size="sm"
                        onClick={() => deleteRow(index)}
                      >
                        Delete
                      </Button>
                    </TableCell>
                    <TableCell>
                      <div className="relative">
                        <Flatpickr
                          value={item.basketDate}
                          onChange={(date) => updateBasket(index, 'basketDate', date[0])}
                          options={datePickerConfig}
                          placeholder="DD/MM/YYYY"
                          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                        <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                          <svg className="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                          </svg>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Select value={item.type} onValueChange={(value) => updateBasket(index, 'type', value)}>
                        <SelectTrigger className="w-full">
                          <SelectValue placeholder="-None-" />
                        </SelectTrigger>
                        <SelectContent>
                          {typeOptions.map((option) => (
                            <SelectItem key={option} value={option}>
                              {option}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </TableCell>
                    <TableCell>
                      <Input
                        value={item.fundCode || ""}
                        onChange={(e) => updateBasket(index, 'fundCode', e.target.value)}
                      />
                    </TableCell>
                    <TableCell>
                      <Input
                        type="number"
                        value={item.invPercentage || ""}
                        onChange={(e) => updateBasket(index, 'invPercentage', e.target.value)}
                      />
                    </TableCell>
                    <TableCell>
                      <Input
                        type="number"
                        value={item.contribution || ""}
                        onChange={(e) => updateBasket(index, 'contribution', e.target.value)}
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <Button onClick={addRow} className="mt-4">
            Add Row
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Annuitant Information</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Is the client the Annuitant?</Label>
              <Select value={formData.isTheClientAnnuitent} onValueChange={(value) => handleChange("isTheClientAnnuitent", value)}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {clientFirstPolicyOptions.map((option) => (
                    <SelectItem key={option} value={option}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-6 sm:col-span-6">
                <Label className="mb-2">Successor Annuitant / Co Applicant</Label>
                <Select value={formData.successorAnnuitantCoApplicant} onValueChange={(value) => handleChange("successorAnnuitantCoApplicant", value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {clientFirstPolicyOptions.map((option) => (
                      <SelectItem key={option} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            {formData.layout === 'RESP' && (
              <div className="lg:col-span-6 sm:col-span-6">
                <Label className="mb-2">Joint Subscriber</Label>
                <Select value={formData.jointSubscriber} onValueChange={(value) => handleChange("jointSubscriber", value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {clientFirstPolicyOptions.map((option) => (
                      <SelectItem key={option} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Number of Annuitants</Label>
              <Input
                type="number"
                value={formData.numberOfAnnuitants || ""}
                onChange={(e) => handleChange("numberOfAnnuitants", e.target.value)}
              />
            </div>
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-6 sm:col-span-6">
                <Label className="mb-2">Name of Co Applicant</Label>
                <Input
                  value={formData.nameofCoApplicant || ""}
                  onChange={(e) => handleChange("nameofCoApplicant", e.target.value)}
                />
              </div>
            )}
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Phone</Label>
              <div className="border rounded-lg p-1.5">
                <PhoneInput
                  value={formData.phone || ""}
                  onChange={(value) => handleChange("phone", value)}
                  defaultCountry="CA"
                  international={true}
                  withCountryCallingCode={true}
                  placeholder="+1 (XXX) XXX-XXXX"
                  maxLength={16}
                />
              </div>
            </div>
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Gender</Label>
              <Select value={formData.gender} onValueChange={(value) => handleChange("gender", value)}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {genderOptions.map((option) => (
                    <SelectItem key={option} value={option}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Relationship to Primary Annuitant</Label>
              <Input
                value={formData.relationshipToPrimaryAnnuitment || ""}
                onChange={(e) => handleChange("relationshipToPrimaryAnnuitment", e.target.value)}
              />
            </div>
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-6 sm:col-span-6">
                <Label className="mb-2">Primary Subscriber /Annuitant Name</Label>
                <Input
                  value={formData.primarySubscriber || ""}
                  onChange={(e) => handleChange("primarySubscriber", e.target.value)}
                />
              </div>
            )}
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Applicant Gender</Label>
              <Select value={formData.applicantGender} onValueChange={(value) => handleChange("applicantGender", value)}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {genderOptions.map((option) => (
                    <SelectItem key={option} value={option}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-6 sm:col-span-6">
                <Label className="mb-2">Is there a Co Applicant?</Label>
                <Select value={formData.isThereCoapplicant} onValueChange={(value) => handleChange("isThereCoapplicant", value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {clientFirstPolicyOptions.map((option) => (
                      <SelectItem key={option} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Email</Label>
              <Input
                type="email"
                value={formData.email || ""}
                onChange={(e) => handleChange("email", e.target.value)}
              />
            </div>
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Date of Birth</Label>
              <div className="relative">
                <Flatpickr
                  value={formData.dateOfBirth}
                  onChange={(date) => handleChange("dateOfBirth", date[0])}
                  options={datePickerConfig}
                  placeholder="DD/MM/YYYY"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                  <svg className="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                  </svg>
                </div>
              </div>
            </div>
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Applicant DOB</Label>
              <div className="relative">
                <Flatpickr
                  value={formData.applicantDOB}
                  onChange={(date) => handleChange("applicantDOB", date[0])}
                  options={datePickerConfig}
                  placeholder="DD/MM/YYYY"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                  <svg className="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd" />
                  </svg>
                </div>
              </div>
            </div>
            <div className="lg:col-span-6 sm:col-span-6">
              <Label className="mb-2">Name of Primary Annuitant</Label>
              <Input
                value={formData.nameOfPrimaryAnnuitment || ""}
                onChange={(e) => handleChange("nameOfPrimaryAnnuitment", e.target.value)}
              />
            </div>
            {formData.layout === 'TFSA' && (
              <div className="lg:col-span-12 sm:col-span-12">
                <Label className="mb-2">Address</Label>
                <Textarea
                  value={formData.address || ""}
                  onChange={(e) => handleChange("address", e.target.value)}
                />
              </div>
            )}
            {formData.layout === 'RESP' && (
              <div className="lg:col-span-4 sm:col-span-6">
                <Label className="mb-2">Spousal Contributor Replacing Subscriber</Label>
                <Select value={formData.spousalContributorReplacingSubscriber} onValueChange={(value) => handleChange("spousalContributorReplacingSubscriber", value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {clientFirstPolicyOptions.map((option) => (
                      <SelectItem key={option} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            {formData.layout === 'RESP' && (
              <div className="lg:col-span-6 sm:col-span-6">
                <Label className="mb-2">Is there a Joint/Replacing Subscriber?</Label>
                <Select value={formData.isThereAJointReplacingSubscriber} onValueChange={(value) => handleChange("isThereAJointReplacingSubscriber", value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Select" />
                  </SelectTrigger>
                  <SelectContent>
                    {clientFirstPolicyOptions.map((option) => (
                      <SelectItem key={option} value={option}>
                        {option}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-4 sm:col-span-6">
                <Label className="mb-2">Principal Occupation</Label>
                <Input
                  value={formData.principalOccupation || ""}
                  onChange={(e) => handleChange("principalOccupation", e.target.value)}
                />
              </div>
            )}
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-12 sm:col-span-12">
                <Label className="mb-2">Address</Label>
                <Textarea
                  value={formData.address || ""}
                  onChange={(e) => handleChange("address", e.target.value)}
                />
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      <div className="flex justify-center gap-4">
        <Button onClick={handlePrev} variant="outline" className="px-6 py-2">
          Prev
        </Button>
        <Button onClick={handleNext} className="px-6 py-2">
          Next
        </Button>
      </div>
    </div>
  );
};

export default AnnuitantInfo;

// client/app/src/views/Policies/investment/component/AnnuitantInfo.vue
<template>
  <div style="margin-bottom:80px;">
    <h5 class="main-heading mb-0 ps-2">Investment Basket</h5>
    <div class="multisteps-form__content">
      <div class="row">
        <div style="width: 100%; overflow: scroll" class="mt-2">
          <table class="table border table-responsive subform">
            <thead class="table subform-table-head text-white">
              <tr>
                <th>#</th>
                <th>Action</th>
                <th>Date</th>
                <th>Type</th>
                <th>Fund Code</th>
                <th>%</th>
                <th>Contribution</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              <tr v-for="(parent, index) in InvestmentBasketData" :key="index">
                <td class="m-auto">{{ index + 1 }}</td>
                <td class="subform-action-center">
                  <a @click.prevent="
                    deleteInvestmentBasketTableRow(
                      index,
                      parent.ROWID
                    )
                    " href="javascript:;" data-bs-toggle="tooltip" data-bs-original-title="Delete product"><i
                      class="fas fa-trash text-secondary" aria-hidden="true"></i></a>
                </td>

                <td>
                  <div class="input-group bg-white" style="width: 200px;">
                    <flat-pickr v-model="parent.basketDate" :config="datePickerConfig" placeholder="DD/MM/YYYY"
                      class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
                      ref="fpDateOfBirth" />
                    <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
                      <i class="fa fa-calendar"></i>
                    </span>
                  </div>
                </td>

                <td>
                  <div style="width: 200px" class="choices" data-type="select-one" tabindex="0" role="listbox"
                    aria-haspopup="true" aria-expanded="false">
                    <div class="select-box">
                      <select v-model="parent.type" id="choices-state"
                        class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                        data-choice="active">
                        <option v-for="(option, index) in typeOptions" :key="index" :value="option"
                          :checked="option === '-None-'">{{ option }}</option>


                      </select>
                    </div>
                  </div>
                </td>
                <td>
                  <input style="width: 200px" v-model="parent.fundCode" type="text"
                    class="form-control form-control-default" isrequired="false" autocomplete="off" />
                </td>
                <td>
                  <input style="width: 200px" v-model="parent.invPercentage" type="number"
                    class="form-control form-control-default" isrequired="false" autocomplete="off" />
                </td>
                <td>
                  <input style="width: 200px" v-model="parent.contribution" type="number"
                    class="form-control form-control-default" isrequired="false" autocomplete="off" />
                </td>
              </tr>
            </tbody>
          </table>
          <button class="btn mb-0 btn-color btn-md null null" type="button"
            @click.prevent="addRowToInvestmentBasketTable">
            Add Row
          </button>
        </div>
      </div>
    </div>
    <h5 class="main-heading mt-3 mb-0 ps-2">Annuitant Information</h5>
    <div class="multisteps-form__content">
      <div class="row ps-2">
        <div class="col-lg-6 col-sm-6 mt-0 mt-sm-0">
          <label class="my-0 mt-2">Is the client the Annuitant?</label>
          <div class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.isTheClientAnnuitent" id="choices-state"
                  class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                  data-choice="active">
                  <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>

                </select>
              </div>
            </div>
          </div>
        </div>
        <div v-if="formData.layout === 'RRSP'" class="col-6 col-sm-4 mt-0 mt-sm-0">
          <label class="my-0 mt-2">Successor Annuitant / Co Applicant</label>
          <div class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.successorAnnuitantCoApplicant" id="successorAnnuitantCoApplicant"
                  class="multisteps-form__select form-control choices__input" name="successorAnnuitantCoApplicant"
                  tabindex="-1" data-choice="active">
                  <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>


                </select>
              </div>
            </div>
          </div>
        </div>
        <div v-if="formData.layout === 'RESP'" class="col-6 col-sm-4 mt-0 mt-sm-0">
          <label class="my-0 mt-2">Joint Subscriber</label>
          <div class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.jointSubscriber" id="choices-state"
                  class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                  data-choice="active">
                  <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>

                </select>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-sm-6 mt-0 mt-sm-0">
          <label class="my-0 mt-2">Number of Annuitants</label>
          <input v-model="formData.numberOfAnnuitants" type="number" class="form-control form-control-default"
            isrequired="false" autocomplete="off" />
        </div>
        <div v-if="formData.layout === 'RRSP'" class="col-6 col-sm-4 mt-0 mt-sm-0">
          <label class="my-0 mt-2">Name of Co Applicant
          </label>
          <input v-model="formData.nameofCoApplicant" type="text" class="form-control form-control-default"
            isrequired="false" autocomplete="off" />
        </div>
        <div class="col-lg-6 col-sm-6 mt-0 mt-sm-0">
          <label class="my-0 mt-2" for="phone">Phone</label>
          <!-- <input v-model="formData.phone" type="number" class="form-control form-control-default" isrequired="false"
            autocomplete="off" /> -->

          <VueTelInput v-model="formData.phone" :defaultCountry="'CA'" :preferredCountries="['CA', 'US', 'IN', 'GB']"
            :enableAutoCountrySelect="true" :mode="'international'" :inputOptions="{
              placeholder: '+1 (XXX) XXX-XXXX',
              inputmode: 'tel',
              maxlength: 16,            // '+' + 15 digits (E.164)
              onInput: handleTelInput   // live sanitize
            }" id="mobile" />
          <span v-if="errors.mobile" class="text-danger">{{ errors.mobile }}</span>

        </div>

        <div class="col-lg-6 col-sm-6 mt-0">
          <label class="my-0 mt-2">Gender</label>

          <div class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.gender" id="choices-state"
                  class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                  data-choice="active">
                  <option v-for="(option, index) in genderOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>
                </select>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-sm-6 mt-0">
          <label class="my-0 mt-2">Relationship to Primary Annuitant</label>
          <input v-model="formData.relationshipToPrimaryAnnuitment" type="text"
            class="form-control form-control-default" isrequired="false" autocomplete="off" />
        </div>

        <div v-show="formData.layout === 'RRSP'" class="col-6 col-sm-4 mt-0">
          <label class="my-0 mt-2">Primary Subscriber /Annuitant Name</label>
          <input v-model="formData.primarySubscriber" type="text" class="form-control form-control-default"
            isrequired="false" autocomplete="off" />
        </div>

        <div class="col-lg-6 col-sm-6 mt-0">
          <label class="my-0 mt-2">Applicant Gender</label>

          <div class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.applicantGender" id="choices-state"
                  class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                  data-choice="active">
                  <option v-for="(option, index) in genderOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>

                </select>
              </div>
            </div>
          </div>
        </div>
        <div v-if="formData.layout === 'RRSP'" class="col-6 col-sm-4 mt-0">
          <label class="my-0 mt-2">Is there a Co Applicant?</label>

          <div class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.isThereCoapplicant" id="choices-state"
                  class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                  data-choice="active">
                  <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>

                </select>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-6 col-sm-6 mt-0">
          <label class="my-0 mt-2">Email</label>
          <input v-model="formData.email" type="email" class="form-control form-control-default" isrequired="false"
            autocomplete="off" />

          <label class="my-0 mt-2">Date of Birth</label>
          <!-- <input v-model="formData.dateOfBirth" type="date" class="form-control form-control-default" isrequired="false"
            autocomplete="off" /> -->

          <div class="input-group bg-white">
            <flat-pickr v-model="formData.dateOfBirth" :config="datePickerConfig" placeholder="DD/MM/YYYY"
              class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
              ref="fpDateOfBirth" />
            <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
              <i class="fa fa-calendar"></i>
            </span>
          </div>


        </div>

        <div class="col-lg-6 col-sm-6 mt-0">
          <label class="my-0 mt-2">Applicant DOB</label>

          <div class="input-group bg-white">
            <flat-pickr v-model="formData.applicantDOB" :config="datePickerConfig" placeholder="DD/MM/YYYY"
              class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
              ref="fpDateOfBirth" />
            <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
        </div>
        <div class="col-lg-6 col-sm-6 mt-0">
          <label class="my-0 mt-2">Name of Primary Annuitant</label>
          <input v-model="formData.nameOfPrimaryAnnuitment" type="text" class="form-control form-control-default"
            isrequired="false" autocomplete="off" />
        </div>
        <div v-if="formData.layout === 'TFSA'" class="col-12 col-sm-4 mt-0">
          <label class="my-0 mt-2">Address</label>
          <textarea v-model="formData.address" type="text" class="form-control form-control-default" isrequired="false"
            autocomplete="off" />
        </div>
        <div v-show="formData.layout === 'RESP'" class="col-4 col-sm-4 mt-2 mt-sm-0">
          <label class="my-0 mt-2">Spousal Contributor Replacing Subscriber</label>
          <div class="choices" data-type="select-one" tabindex="0" role="spousalContributorReplacingSubscriber"
            aria-haspopup="true" aria-expanded="false">
            <div class="select-box" :class="{
              highlight: errors.spousalContributorReplacingSubscriber,
            }">
              <select required v-model="formData.spousalContributorReplacingSubscriber"
                id="spousalContributorReplacingSubscriber" class="multisteps-form__select form-control choices__input"
                name="spousalContributorReplacingSubscriber" tabindex="-1" data-choice="active">
                <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                  :checked="option === '-None-'">{{ option }}</option>

              </select>
              <span v-if="errors.spousalContributorReplacingSubscriber" class="error input-error-font-size">
                {{ errors.spousalContributorReplacingSubscriber }}
              </span>
            </div>
          </div>
        </div>
        <div v-if="formData.layout === 'RESP'" class="col-6 col-sm-4 mt-0 mt-sm-0 ">
          <label v-if="formData.layout === 'RESP'" class="my-0 mt-2">Is there a Joint/Replacing Subscriber?</label>
          <div v-if="formData.layout === 'RESP'" class="">
            <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
              aria-expanded="false">
              <div class="select-box">
                <select v-model="formData.isThereAJointReplacingSubscriber" id="choices-state"
                  class="multisteps-form__select form-control choices__input" name="choices-state" tabindex="-1"
                  data-choice="active">
                  <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                    :checked="option === '-None-'">{{ option }}</option>

                </select>
              </div>
            </div>
          </div>
        </div>
        <div v-if="formData.layout === 'RRSP'" class="col-lg-4 col-sm-4 mt-0 mt-sm-0">
          <label class="my-0 mt-2">Principal Occupation</label>

          <div class="">
            <input :class="{ highlight: errors.principalOccupation }" v-model="formData.principalOccupation"
              id="principalOccupation" type="text" class="form-control form-control-default" name="" isrequired="false"
              autocomplete="off" />
            <span v-if="errors.principalOccupation" class="error input-error-font-size">{{ errors.principalOccupation
            }}</span>
          </div>
        </div>
        <div v-if="formData.layout === 'RRSP'" class="col-12 col-sm-4 mt-0">
          <label class="my-0 mt-2">Address</label>
          <textarea v-model="formData.address" type="text" class="form-control form-control-default" isrequired="false"
            autocomplete="off" />
        </div>
      </div>
    </div>
    <div class="button-row d-flex justify-content-center mt-4 gap-4">
      <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" type="button" @click="prevStep">
        Prev
      </button>
      <button class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" type="button" @click.prevent="nextStep">
        Next
      </button>
    </div>
  </div>
</template>
<style></style>
<script>
import { clientFirstPolicyOptions, typeOptions, genderOptions } from "../../utils/picklist.js";
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
import { VueTelInput } from 'vue-tel-input'
import 'vue-tel-input/dist/vue-tel-input.css'
export default {
  components: { flatPickr, VueTelInput },
  props: {
    annuitantInfo: {
      type: Object,
      required: true
    }
  },
  watch: {
    annuitantInfo: {
      handler() {
        this.formData = { ...this.annuitantInfo };
        this.InvestmentBasketData = this.annuitantInfo.InvestmentBasketData || [];
      },
      deep: true,
      immediate: true,
    }
  },
  data() {
    return {

      datePickerConfig: {
        dateFormat: "d/m/Y", // DD/MM/YYYY
        allowInput: true
      },
      dateTimePickerConfig: {
        dateFormat: "d/m/Y H:i", // DD/MM/YYYY HH:mm
        allowInput: true,
        enableTime: true,
        time_24hr: true
      },
      clientFirstPolicyOptions: { ...clientFirstPolicyOptions },
      typeOptions: { ...typeOptions },
      genderOptions: { ...genderOptions },
      InvestmentBasketData: [],
      errors: {},
      formData: { ...this.annuitantInfo },
    }
  },
  methods: {



    handleTelInput(e) {
      const raw = e?.target?.value ?? '';
      // keep leading +, strip everything else non-digit
      let cleaned = raw.replace(/(?!^)\+/g, '');       // remove extra '+' if any
      cleaned = cleaned.replace(/[^+\d]/g, '');        // only '+' and digits
      // limit to '+' + 15 digits
      const plus = cleaned.startsWith('+') ? '+' : '';
      const digits = cleaned.replace(/\D/g, '').slice(0, 15);
      cleaned = plus + digits;
      e.target.value = cleaned;
      this.formData.mobile = cleaned;
      // clear error as user fixes
      if (this.errors.mobile) delete this.errors.mobile;
    },
    nextStep() {
      this.errors = validateMandatoryFields(this.formData, mandatory);

      const mobile = (this.formData.mobile || "").replace(/\s|-/g, "");

      if (mobile) {
        if (!mobile.startsWith("+")) {
          this.errors.mobile = "Country code is required (e.g. +1...)";
        } else if (/^\+1/.test(mobile) && !/^\+1\d{10}$/.test(mobile)) {
          this.errors.mobile = "Canadian number must be +1 followed by 10 digits";
        } else if (!/^\+\d{8,15}$/.test(mobile)) {
          this.errors.mobile = "Phone must be in international format (e.g. +1234567890)";
        }
      }
    },
    openDatePicker() {
      if (this.$refs.fpDateOfBirth && this.$refs.fpDateOfBirth.fp) {
        this.$refs.fpDateOfBirth.fp.open()
      }
    },



    addRowToInvestmentBasketTable() {
      this.InvestmentBasketData.push({
        contribution: '',
        invPercentage: '',
        fundCode: '',
        type: '',
        basketDate: '',
      });
    },
    deleteInvestmentBasketTableRow(index) {
      this.InvestmentBasketData.splice(index, 1);
    },
    nextStep() {
      this.$emit('next', { ...this.formData, InvestmentBasketData: this.InvestmentBasketData });
    },
    prevStep() {
      this.$emit('previous');
    },
  }
}
</script>
