// client/app/src/views/leads/leadAdvisorForm/leadAdvisorFormComponents/LeadManagementInformation.vue
<template>
    <div>
      <h5 class="main-heading mt-2 ps-2">Lead Management History</h5>
      <div style="width: 100%; overflow: scroll">
        <table class="table border table-responsive subform">
          <thead class="table subform-table-head text-white">
            <tr>
              <th>#</th>
              <th>Actions</th>
              <th>Interaction Type</th>
              <th>Date/Time Of Interaction</th>
              <th>Contact Attempt</th>
              <th>Time Spent (Mins)</th>
              <th style="min-width: 20rem;" class="text-center">Comments</th>
              <th>Interaction Outcome</th>
              <th>Probability Of Closure</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <tr v-for="(parent, index) in subform" :key="index">
              <td class="m-auto">{{ index + 1 }}</td>
              <td>
                <a @click.prevent="deleteLeadsRow(index)" href="javascript:;" data-bs-toggle="tooltip" data-bs-original-title="Delete product">
                  <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
                </a>
              </td>
              <td>
                <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true" aria-expanded="false">
                  <div class="select-box">
                    <select v-model="parent.interactionType" class="multisteps-form__select form-control choices__input" name="choices-state">
                      <option value="Email">Email</option>
                      <option value="Call">Call</option>
                      <option value="Meeting">Meeting</option>
                      <!-- Add other options as needed -->
                    </select>
                  </div>
                </div>
              </td>
              <td>
                <input v-model="parent.timeOfInteraction" type="datetime-local" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
                <input v-model="parent.contactAttempt" type="number" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
                <input v-model="parent.timeSpent" type="number" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
                <textarea v-model="parent.comments" class="form-control form-control-default" rows="2" cols="12"></textarea>
              </td>
              <td>
                <input v-model="parent.interactionOutcome" type="text" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
                <input v-model="parent.probabilityOfClosure" type="number" class="form-control form-control-default" autocomplete="off">
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <button class="btn mb-0 btn-color btn-md" type="button" @click.prevent="addRowToLeadDataTable">
        Add Row
      </button>
    </div>
    <div class="button-row d-flex justify-content-center mt-4 gap-4">
      <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" @click="previousStep" type="button">Prev</button>
      <button class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" @click.prevent="nextStep" type="button">Next</button>       
      </div>
  </template>
  
  <script>
  export default {
    name: "LeadManagementHistory",
    props:{

      LeadManagementInformation:{
        type: Object,
        required: true
      }
    },
    data() {
      return {
        subform: []
      };
    },

    watch: {
      LeadManagementInformation:{
      handler(){
        this.subform = this.LeadManagementInformation.LeadData || [];
        },
        immediate: true,
        deep: true
      }
    },
    methods: {
      nextStep() {
      this.$emit('next', {"LeadData":this.subform});
    },
    addRowToLeadDataTable() {
        this.subform.push({
          interactionType: "",
          timeOfInteraction: "",
          contactAttempt: "",
          timeSpent: "",
          comments: "",
          interactionOutcome: "",
          probabilityOfClosure: ""
        });
      },
      deleteLeadsRow(index) {
        this.subform.splice(index, 1);
      }
    }
  };
  </script>
  
  <style scoped>
  .main-heading {
    font-weight: 500 !important;
  }
  
  .form-control-default {
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 0.5rem;
    width: 100%;
  }
  
  .my-0 {
    margin-bottom: 0 !important;
  }
  </style>

// frontend/src/features/crm/pages/advisor/leadAdvisorFormComponents/LeadManagementInformation.jsx
import React, { useState, useEffect } from 'react';
import { FormCard, FormField } from '@/components/custom/CustomFormComponents';
import { Input } from '@/components/ui/input';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

const LeadManagementInformation = ({ LeadManagementInformation, onNext, onPrevious }) => {
  const [subform, setSubform] = useState([]);

  useEffect(() => {
    setSubform(LeadManagementInformation.LeadData || []);
  }, [LeadManagementInformation]);

  const addRowToLeadDataTable = () => {
    setSubform(prev => [...prev, {
      interactionType: "",
      timeOfInteraction: "",
      contactAttempt: "",
      timeSpent: "",
      comments: "",
      interactionOutcome: "",
      probabilityOfClosure: ""
    }]);
  };

  const deleteLeadsRow = (index) => {
    setSubform(prev => prev.filter((_, i) => i !== index));
  };

  const handleInputChange = (index, field, value) => {
    setSubform(prev => prev.map((item, i) => i === index ? { ...item, [field]: value } : item));
  };

  const handleNext = () => {
    onNext({ LeadData: subform });
  };

  const handlePrevious = () => {
    onPrevious();
  };

  return (
    <div>
      <FormCard title="Lead Management History">
        <div className="overflow-x-auto">
          <table className="table table-bordered table-responsive">
            <thead className="table-dark">
              <tr>
                <th>#</th>
                <th>Actions</th>
                <th>Interaction Type</th>
                <th>Date/Time Of Interaction</th>
                <th>Contact Attempt</th>
                <th>Time Spent (Mins)</th>
                <th className="text-center">Comments</th>
                <th>Interaction Outcome</th>
                <th>Probability Of Closure</th>
              </tr>
            </thead>
            <tbody>
              {subform.map((item, index) => (
                <tr key={index}>
                  <td>{index + 1}</td>
                  <td>
                    <button
                      onClick={() => deleteLeadsRow(index)}
                      className="btn btn-sm btn-danger"
                    >
                      <i className="fas fa-trash"></i>
                    </button>
                  </td>
                  <td>
                    <Select
                      value={item.interactionType || ''}
                      onValueChange={(value) => handleInputChange(index, 'interactionType', value)}
                    >
                      <SelectTrigger className="w-full">
                        <SelectValue placeholder="Select" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="Email">Email</SelectItem>
                        <SelectItem value="Call">Call</SelectItem>
                        <SelectItem value="Meeting">Meeting</SelectItem>
                      </SelectContent>
                    </Select>
                  </td>
                  <td>
                    <Input
                      type="datetime-local"
                      value={item.timeOfInteraction || ''}
                      onChange={(e) => handleInputChange(index, 'timeOfInteraction', e.target.value)}
                    />
                  </td>
                  <td>
                    <Input
                      type="number"
                      value={item.contactAttempt || ''}
                      onChange={(e) => handleInputChange(index, 'contactAttempt', e.target.value)}
                    />
                  </td>
                  <td>
                    <Input
                      type="number"
                      value={item.timeSpent || ''}
                      onChange={(e) => handleInputChange(index, 'timeSpent', e.target.value)}
                    />
                  </td>
                  <td>
                    <Textarea
                      value={item.comments || ''}
                      onChange={(e) => handleInputChange(index, 'comments', e.target.value)}
                      rows={2}
                      cols={12}
                    />
                  </td>
                  <td>
                    <Input
                      value={item.interactionOutcome || ''}
                      onChange={(e) => handleInputChange(index, 'interactionOutcome', e.target.value)}
                    />
                  </td>
                  <td>
                    <Input
                      type="number"
                      value={item.probabilityOfClosure || ''}
                      onChange={(e) => handleInputChange(index, 'probabilityOfClosure', e.target.value)}
                    />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <button
          className="btn btn-primary mt-3"
          type="button"
          onClick={addRowToLeadDataTable}
        >
          Add Row
        </button>
      </FormCard>
    </div>
  );
};

export default LeadManagementInformation;
