// client/app/src/views/demo/dealComponents/Claims.vue
<template>
  <h5 class="main-heading mb-0">Claims</h5>
  <div>
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Any Current Claims on this Policy?</label>
        <select v-model="formData.currentClaims" class="form-select">
          <option
            v-for="(option, index) in claims"
            :key="index"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Any Past Claims on this Policy?</label>
        <select v-model="formData.pastClaims" class="form-select">
          <option
            v-for="(option, index) in objectType"
            :key="index"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Reason of Claim</label>
        <textarea
          v-model="formData.reasonOfClaim"
          class="form-control form-control-default"
          rows="1"
        ></textarea>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Claim Outcome</label>
        <select v-model="formData.claimOutcome" class="form-select">
          <option
            v-for="(option, index) in approval"
            :key="index"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Claim Submitted?</label>
        <select v-model="formData.claimSubmitted" class="form-select">
          <option
            v-for="(option, index) in objectType"
            :key="index"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Claim Amount</label>
        <input
          v-model="formData.claimAmount"
          type="number"
          placeholder=""
          class="form-control form-control-default"
        />
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Date of Claim</label>
        <input
          v-model="formData.dateOfClaim"
          type="date"
          class="form-control"
        />
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Claim Closed On-</label>
        <input
          v-model="formData.claimClosedOn"
          type="date"
          class="form-control"
        />
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Amount Settled</label>
        <input
          v-model="formData.amountSettled"
          type="number"
          placeholder=""
          class="form-control form-control-default"
        />
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Settlement or Rejection Observations</label>
        <textarea
          v-model="formData.settlementOrRejectionObservations"
          class="form-control form-control-default"
          rows="4"
        ></textarea>
      </div>
    </div>
  </div>
  <div class="button-row d-flex justify-content-center mt-2 gap-4">
    <button
      class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev"
      type="button"
      @click="previousStep"
    >
      Prev
    </button>
    <button
      class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next"
      @click.prevent="nextStep"
      type="button"
    >
      Next
    </button>
  </div>
</template>

<script>
import {claims,objectType,approval,renewal} from "../utils/picklist.js";
export default {
  name: "InsuranceInquiryForm",
  props: {
    getdealClais: {
      type: Function,
      required: true,
    },
    Claims: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      formData: { ...this.Claims },
      objectType : { ...objectType },
      approval : { ...approval },
      renewal : { ...renewal },
      claims : { ...claims },
    };
  },
  watch: {
    Claims: {
      handler(formData) {
        this.formData = { ...this.Claims };
        console.log("this formData Claims", formData);
      },
      immediate: true,
      deep: true,
    },
  },
  methods: {
    sendData() {
      this.getdealClais(this.formData);
    },
    nextStep() {
      this.$emit("next", this.formData);
    },
    previousStep() {
      this.$emit("previous");
    },
  },
};
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
</style>

// frontend/src/features/crm/pages/deals/dealFormComponents/Claims.jsx
import React, { useState, useEffect } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { claims, objectType, approval } from "../utils/picklist";

const Claims = ({ formData, setFormData }) => {
  const [claimsData, setClaimsData] = useState(formData.claims || []);

  useEffect(() => {
    setFormData({ ...formData, claims: claimsData });
  }, [claimsData]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleClaimChange = (index, field, value) => {
    const updatedClaims = [...claimsData];
    updatedClaims[index] = { ...updatedClaims[index], [field]: value };
    setClaimsData(updatedClaims);
  };

  const addRow = () => {
    setClaimsData([...claimsData, {
      reasonOfClaim: "",
      claimOutcome: "",
      claimSubmitted: "",
      claimAmount: "",
      dateOfClaim: "",
      claimClosedOn: "",
      amountSettled: "",
      settlementOrRejectionObservations: ""
    }]);
  };

  const deleteRow = (index) => {
    const updatedClaims = claimsData.filter((_, i) => i !== index);
    setClaimsData(updatedClaims);
  };

  return (
    <div className="claims">
      <h5 className="main-heading mb-4 ps-2">Claims</h5>
      <div className="grid grid-cols-3 gap-4 ps-2 mb-3">
        <div className="mb-3">
          <Label className="my-0">Current Claims</Label>
          <Select
            value={formData.currentClaims || ""}
            onValueChange={(value) => setFormData({ ...formData, currentClaims: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {claims.map((claim) => (
                <SelectItem key={claim} value={claim}>
                  {claim}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Past Claims</Label>
          <Select
            value={formData.pastClaims || ""}
            onValueChange={(value) => setFormData({ ...formData, pastClaims: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {claims.map((claim) => (
                <SelectItem key={claim} value={claim}>
                  {claim}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
      <div style={{ width: "100%", overflow: "scroll" }}>
        <Table className="border table-responsive subform">
          <TableHeader className="subform-table-head text-white">
            <TableRow>
              <TableHead>#</TableHead>
              <TableHead>Actions</TableHead>
              <TableHead>Reason of Claim</TableHead>
              <TableHead>Claim Outcome</TableHead>
              <TableHead>Claim Submitted</TableHead>
              <TableHead>Claim Amount</TableHead>
              <TableHead>Date of Claim</TableHead>
              <TableHead>Claim Closed On</TableHead>
              <TableHead>Amount Settled</TableHead>
              <TableHead>Settlement or Rejection Observations</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="table-group-divider">
            {claimsData.map((claim, index) => (
              <TableRow key={index}>
                <TableCell className="m-auto">{index + 1}</TableCell>
                <TableCell>
                  <Button
                    type="button"
                    onClick={() => deleteRow(index)}
                    variant="destructive"
                    size="sm"
                  >
                    <i className="fas fa-trash"></i>
                  </Button>
                </TableCell>
                <TableCell>
                  <Input
                    type="text"
                    value={claim.reasonOfClaim || ""}
                    onChange={(e) => handleClaimChange(index, "reasonOfClaim", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Select
                    value={claim.claimOutcome || ""}
                    onValueChange={(value) => handleClaimChange(index, "claimOutcome", value)}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select" />
                    </SelectTrigger>
                    <SelectContent>
                      {approval.map((app) => (
                        <SelectItem key={app} value={app}>
                          {app}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <Select
                    value={claim.claimSubmitted || ""}
                    onValueChange={(value) => handleClaimChange(index, "claimSubmitted", value)}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select" />
                    </SelectTrigger>
                    <SelectContent>
                      {objectType.map((opt) => (
                        <SelectItem key={opt} value={opt}>
                          {opt}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <Input
                    type="number"
                    value={claim.claimAmount || ""}
                    onChange={(e) => handleClaimChange(index, "claimAmount", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="date"
                    value={claim.dateOfClaim || ""}
                    onChange={(e) => handleClaimChange(index, "dateOfClaim", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="date"
                    value={claim.claimClosedOn || ""}
                    onChange={(e) => handleClaimChange(index, "claimClosedOn", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="number"
                    value={claim.amountSettled || ""}
                    onChange={(e) => handleClaimChange(index, "amountSettled", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Textarea
                    value={claim.settlementOrRejectionObservations || ""}
                    onChange={(e) => handleClaimChange(index, "settlementOrRejectionObservations", e.target.value)}
                    rows="2"
                  />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <Button type="button" onClick={addRow} className="mb-0 btn-color btn-md">
        Add Row
      </Button>
    </div>
  );
};

export default Claims;
