// client/app/src/views/deals/dealComponents/DealInformation.vue
<template>
  <div>
    <!-- Insurance Inquiry Form -->
    <h5 class="main-heading mb-0 ps-2">Deal Info</h5>
    <div style="">
      <!-- Potential Business (Policy Values) -->
      <div class=" row mt-3 ps-2 ">
        <!-- Deal Name -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0"
            >Deal Name <span class="text-danger">*</span></label
          >
            <input
              v-model="formData.dealName"
              type="text"
              class="form-control form-control-default"
            />
            <span v-if="errors.dealName" class="text-danger">{{
              errors.dealName
            }}</span>
        </div>
        <!-- Deal Owner -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Deal Owner <span class="text-danger">*</span></label>
          <select
            class="form-select"
            id="dealOwnerOptions"
            v-model="formData.dealOwner"
          >
            <option value="" selected class="text-muted">Select Owner</option>
            <option
              v-for="owner in ownersArr"
              :key="owner.ROWID"
              :value="owner.ROWID"
            >
              {{ owner.name }}
            </option>
          </select>
          <span v-if="errors.dealOwner" class="text-danger">{{
            errors.dealOwner
          }}</span>
        </div>
        <!-- Insurance Lead Source -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Insurance Lead Source </label>
          <select v-model="formData.insuranceLeadSource" class="form-select">
            <option
              v-for="(option, index) in insuranceLead"
              :key="index"
              :value="option"
            >
              {{ option }}
            </option>
          </select>
        </div>
      </div>

      <!-- Currency -->
      <div class="row ps-2">
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Currency</label>
          <select v-model="formData.currency" class="form-select">
            <option
              v-for="(option, index) in currency"
              :key="index"
              :value="option"
            >
              {{ option }}
            </option>
          </select>
        </div>
        <!-- Insurance Lead Lookup -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Insurance Lead Lookup</label>
          <select
            class="form-select"
            id="leadOwner"
            v-model="formData.insuranceLeadLookup"
          >
            <option value="" selected class="text-muted">
              Select Lead Lookup
            </option>
            <option
              v-for="lead in leadsArr"
              :key="lead.ROWID"
              :value="lead.ROWID"
            >
              {{ lead.name }}
            </option>
          </select>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Type</label>
          <select v-model="formData.type" class="form-select">
            <option
              v-for="(option, index) in type"
              :key="index"
              :value="option"
            >
              {{ option }}
            </option>
          </select>
        </div>
      </div>

      <!-- Stage -->
      <div class=" row mt-3 ps-2">
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Stage</label>
          <select v-model="formData.stage" class="form-select">
            <option
              v-for="(option, index) in stage"
              :key="index"
              :value="option"
            >
              {{ option }}
            </option>
          </select>
        </div>

        <!-- Contact Name -->
        <div class="col-lg-4 mt-2 col-md-4 col-sm-12">
          <label class="my-0">Contact Name <span class="text-danger">*</span></label>
          <select
            class="form-select"
            id="contactOwner"
            v-model="formData.contactName"
          >
            <option value="" disabled selected class="text-muted">
              Select Contact
            </option>
            <option
              v-for="contact in contactsArr"
              :key="contact.ROWID"
              :value="contact.ROWID"
            >
              {{ contact.name }}
            </option>
          </select>
          <span v-if="errors.contactName" class="text-danger">{{
            errors.contactName
          }}</span>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Forecast Category</label>
          <select v-model="formData.forecastCategory" class="form-select">
            <option
              v-for="(option, index) in forecastCategory"
              :key="index"
              :value="option"
            >
              {{ option }}
            </option>
          </select>
        </div>
      </div>
      <div class="row ps-2">
        <!--Location Name -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Location Name <span class="text-danger">*</span> </label>
          <select
            class="form-select"
            id="locationNameOwner"
            v-model="formData.locationName"
          >
            <option value="" selected class="text-muted">
              Select Location
            </option>
            <option
              v-for="location in locationArr"
              :key="location.ROWID"
              :value="location.ROWID"
            >
              {{ location.name }}
            </option>
          </select>
          <span v-if="errors.locationName" class="text-danger">{{
            errors.locationName
          }}</span>
        </div>
        <!--insurance Lead -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Insurance Lead <span class="text-danger">*</span></label>
          <select
            class="form-select"
            id="leadOwner"
            v-model="formData.insuranceLead"
          >
            <option value="" selected class="text-muted">Select Lead</option>
            <option
              v-for="lead in leadsArr"
              :key="lead.ROWID"
              :value="lead.ROWID"
            >
              {{ lead.name }}
            </option>
          </select>
          <span v-if="errors.insuranceLead" class="text-danger">{{
            errors.insuranceLead
          }}</span>
          <!-- <input v-model="formData.insuranceLead" type="text" class="form-control form-control-default" /> -->
        </div>
        <!--Exchange Rate -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">Exchange Rate</label>
          <input
            v-model="formData.exchangeRate"
            type="number"
            class="form-control form-control-default"
          />
        </div>
      </div>
      <!--Re-run round robin -->
      <div class=" row mt-3 ps-2">
        <!--PhoneBurner Follow Up Date -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <label class="my-0">PhoneBurner Follow Up Date</label>
          <input
            v-model="formData.phoneBurnerFollowUpDate"
            type="date"
            class="form-control"
          />
        </div>
        <!--Round Robin Assignment Time -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <div>
            <label class="my-0 mx-2" for="roundRobinAssignmentTime"
              >Round Robin Assignment Time
            </label>
            <input
              type="datetime-local"
              class="form-control border"
              id="roundRobinAssignmentTime"
              v-model="formData.roundRobinAssignmentTime"
            />
          </div>
        </div>
        <!--PhoneBurner Last Call Time  -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <div>
            <label class="my-0 mx-2" for="phoneBurnerLastCallTime"
              >PhoneBurner Last Call Time
            </label>
            <input
              type="datetime-local"
              class="form-control border"
              id="phoneBurnerLastCallTime"
              v-model="formData.phoneBurnerLastCallTime"
            />
          </div>
        </div>
      </div>
      <div class=" row mt-3 ps-2">
        <div class="col-lg-4 col-md-4 col-sm-12">
          <div>
            <label class="my-0 mx-2" for="phoneBurnerLastCallTime"
              >PhoneBurner Last Call Outcome</label
            >
            <input
              type="text"
              class="form-control border"
              id="phoneBurnerLastCallOutcome"
              v-model="formData.phoneBurnerLastCallOutcome"
            />
          </div>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-12">
          <div class="d-flex justify-content-start align-items-center mt-2">
            <label class="my-0 mx-2" for="reRunRoundRobin"
              >Re-run round robin</label
            >
            <input
              type="checkbox"
              class="form-check-input border"
              id="reRunRoundRobin"
              v-model="formData.reRunRoundRobin"
              style="width: 16px; height: 16px;" 
            />
          </div>
        </div>
      </div>
      <div class=" row mt-3 ps-2">
        <div class="col-lg-4 col-md-4 col-sm-12">
          <div class="d-flex justify-content-start align-items-center mt-2">
            <label class="my-0 mx-2" for="emailRoundRobinOwner"
              >Email Round Robin Owner</label
            >
            <input
              type="checkbox"
              class="form-check-input border"
              id="emailRoundRobinOwner"
              v-model="formData.emailRoundRobinOwner"
              style="width: 16px; height: 16px;" 
            />
          </div>
        </div>
        <!-- Round Robin Processed-->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <div class="d-flex justify-content-start align-items-center mt-2">
            <label class="my-0 mx-2" for="roundRobinProcessed"
              >Round Robin Processed</label
            >
            <input
              type="checkbox"
              class="form-check-input border"
              id="roundRobinProcessed"
              v-model="formData.roundRobinProcessed"
              style="width: 16px; height: 16px;" 
            />
          </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12">
          <div class="d-flex justify-content-start align-items-center mt-2">
            <label class="my-0 mx-2" for="eligibleOwner"
              >Eligible Round Robin Owner Found</label
            >
            <input
              type="checkbox"
              class="form-check-input border"
              id="eligibleOwner"
              v-model="formData.eligibleRoundRobinOwnerFound"
              style="width: 16px; height: 16px;" 
            />
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="button-row d-flex justify-content-center mt-4 gap-4 space" >
    <!-- <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" type="button"  @click.prevent="previousStep">Prev</button> -->
    <button
      class="btn mb-2 bg-gradient-dark btn-md null null js-btn-next"
      @click.prevent="nextStep"
      type="button"
    >
      Next
    </button>
  </div>
</template>

<script>
import {
  insuranceLead,
  dealOwnerOptions,
  stage,
  forecastCategory,
  type,
  currency,
} from "../utils/picklist.js";
import mandatory from "../utils/mandatory.js";
import validateMandatoryFields from "../../utils/util-js/validate.js";

export default {
  name: "InsuranceInquiryForm",
  props: {
    DealInformation: {
      type: Object,
    },
    getDealInfo: {
      type: Function,
      required: true,
    },
    owners: {
      type: Array,
      required: true,
    },
    contacts: {
      type: Array,
      required: true,
    },
    location: {
      type: Array,
      required: true,
    },
    leads: {
      type: Array,
      required: true,
    },
  },
  data() {
    return {
      formData: { ...this.DealInformation },
      ownersArr: [...this.owners],
      contactsArr: [...this.contacts],
      locationArr: [...this.location],
      leadsArr: [...this.leads],
      errors:{},
      insuranceLead: [...insuranceLead],
      dealOwnerOptions: [...dealOwnerOptions],
      stage: [...stage],
      forecastCategory: [...forecastCategory],
      type: [...type],
      currency: [...currency],
    };
  },
  watch: {
    DealInformation: {
      handler(formData) {
        formData = { ...this.DealInformation };
        console.log("this formData", formData);
      },
      immediate: true,
      deep: true,
    },
    owners: {
      handler(ownersArr) {
        ownersArr = this.owners;
        console.log("this ownersArr =========>>>>>>>>>", ownersArr);
      },
      immediate: true,
      deep: true,
    },
    contacts: {
      handler(contactsArr) {
        contactsArr = this.contacts;
        console.log("this contactsArr", contactsArr);
      },
      immediate: true,
      deep: true,
    },
    location: {
      handler(locationArr) {
        locationArr = this.location;
        console.log("this locationArr", locationArr);
      },
      immediate: true,
      deep: true,
    },
    leads: {
      handler(leadsArr) {
        leadsArr = this.leads;
        console.log("this leadsArr", leadsArr);
      },
      immediate: true,
      deep: true,
    },
  },
  methods: {
    nextStep() {
      this.errors = validateMandatoryFields(this.formData, mandatory);
      const validateFields = Object.keys(this.errors).length === 0;
      if(validateFields){
      this.$emit("next", this.formData);
    }
  },
    previousStep() {
      this.$emit("previous");
    },
  },
};
</script>
<style scoped>
.main-heading {
  font-weight: 500 !important;
}
.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}
.my-0 {
  margin-bottom: 0 !important;
}
@media screen and (max-width:500px) {
  .space{
    margin-bottom:100px;
  }
}
</style>

// frontend/src/features/crm/pages/deals/dealFormComponents/DealInformation.jsx
import React from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import {
  insuranceLead,
  stage,
  forecastCategory,
  type,
  currency,
  objectType,
} from "../utils/picklist";

const DealInformation = ({ formData, setFormData, owners, contacts, locations, leads, errors }) => {
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  return (
    <div className="deal-information container-fluid">
      <h5 className="main-heading mb-4 ps-2">Deal Info</h5>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">Deal Name <span className="text-red-500">*</span></Label>
          <Input
            type="text"
            name="dealName"
            value={formData.dealName || ""}
            onChange={handleChange}
            className={`w-full ${errors.dealName ? "border-red-500" : ""}`}
          />
          {errors.dealName && <div className="text-red-500 text-sm">{errors.dealName}</div>}
        </div>
        <div className="mb-3">
          <Label className="my-0">Deal Owner <span className="text-red-500">*</span></Label>
          <Select
            value={formData.dealOwner || ""}
            onValueChange={(value) => setFormData({ ...formData, dealOwner: value })}
          >
            <SelectTrigger className={`w-full ${errors.dealOwner ? "border-red-500" : ""}`}>
              <SelectValue placeholder="Select Owner" />
            </SelectTrigger>
            <SelectContent>
              {owners.map((owner) => (
                <SelectItem key={owner.ROWID} value={owner.ROWID}>
                  {owner.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.dealOwner && <div className="text-red-500 text-sm">{errors.dealOwner}</div>}
        </div>
        <div className="mb-3">
          <Label className="my-0">Insurance Lead Source</Label>
          <Select
            value={formData.insuranceLeadSource || ""}
            onValueChange={(value) => setFormData({ ...formData, insuranceLeadSource: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Source" />
            </SelectTrigger>
            <SelectContent>
              {insuranceLead.map((option) => (
                <SelectItem key={option} value={option}>
                  {option}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">Currency</Label>
          <Select
            value={formData.currency || ""}
            onValueChange={(value) => setFormData({ ...formData, currency: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Currency" />
            </SelectTrigger>
            <SelectContent>
              {currency.map((curr) => (
                <SelectItem key={curr} value={curr}>
                  {curr}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Insurance Lead Lookup</Label>
          <Select
            value={formData.insuranceLeadLookup || ""}
            onValueChange={(value) => setFormData({ ...formData, insuranceLeadLookup: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Lead Lookup" />
            </SelectTrigger>
            <SelectContent>
              {leads.map((lead) => (
                <SelectItem key={lead.ROWID} value={lead.ROWID}>
                  {lead.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Type</Label>
          <Select
            value={formData.type || ""}
            onValueChange={(value) => setFormData({ ...formData, type: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Type" />
            </SelectTrigger>
            <SelectContent>
              {type.map((t) => (
                <SelectItem key={t} value={t}>
                  {t}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">Stage</Label>
          <Select
            value={formData.stage || ""}
            onValueChange={(value) => setFormData({ ...formData, stage: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Stage" />
            </SelectTrigger>
            <SelectContent>
              {stage.map((s) => (
                <SelectItem key={s} value={s}>
                  {s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Contact Name <span className="text-red-500">*</span></Label>
          <Select
            value={formData.contactName || ""}
            onValueChange={(value) => setFormData({ ...formData, contactName: value })}
          >
            <SelectTrigger className={`w-full ${errors.contactName ? "border-red-500" : ""}`}>
              <SelectValue placeholder="Select Contact" />
            </SelectTrigger>
            <SelectContent>
              {contacts.map((contact) => (
                <SelectItem key={contact.ROWID} value={contact.ROWID}>
                  {contact.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.contactName && <div className="text-red-500 text-sm">{errors.contactName}</div>}
        </div>
        <div className="mb-3">
          <Label className="my-0">Forecast Category</Label>
          <Select
            value={formData.forecastCategory || ""}
            onValueChange={(value) => setFormData({ ...formData, forecastCategory: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select Category" />
            </SelectTrigger>
            <SelectContent>
              {forecastCategory.map((cat) => (
                <SelectItem key={cat} value={cat}>
                  {cat}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">Location Name <span className="text-red-500">*</span></Label>
          <Select
            value={formData.locationName || ""}
            onValueChange={(value) => setFormData({ ...formData, locationName: value })}
          >
            <SelectTrigger className={`w-full ${errors.locationName ? "border-red-500" : ""}`}>
              <SelectValue placeholder="Select Location" />
            </SelectTrigger>
            <SelectContent>
              {locations.map((location) => (
                <SelectItem key={location.ROWID} value={location.ROWID}>
                  {location.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.locationName && <div className="text-red-500 text-sm">{errors.locationName}</div>}
        </div>
        <div className="mb-3">
          <Label className="my-0">Insurance Lead <span className="text-red-500">*</span></Label>
          <Select
            value={formData.insuranceLead || ""}
            onValueChange={(value) => setFormData({ ...formData, insuranceLead: value })}
          >
            <SelectTrigger className={`w-full ${errors.insuranceLead ? "border-red-500" : ""}`}>
              <SelectValue placeholder="Select Lead" />
            </SelectTrigger>
            <SelectContent>
              {leads.map((lead) => (
                <SelectItem key={lead.ROWID} value={lead.ROWID}>
                  {lead.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.insuranceLead && <div className="text-red-500 text-sm">{errors.insuranceLead}</div>}
        </div>
        <div className="mb-3">
          <Label className="my-0">Exchange Rate</Label>
          <Input
            type="number"
            name="exchangeRate"
            value={formData.exchangeRate || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">PhoneBurner Follow Up Date</Label>
          <Input
            type="date"
            name="phoneBurnerFollowUpDate"
            value={formData.phoneBurnerFollowUpDate || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Round Robin Assignment Time</Label>
          <Input
            type="datetime-local"
            name="roundRobinAssignmentTime"
            value={formData.roundRobinAssignmentTime || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">PhoneBurner Last Call Time</Label>
          <Input
            type="datetime-local"
            name="phoneBurnerLastCallTime"
            value={formData.phoneBurnerLastCallTime || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">PhoneBurner Last Call Outcome</Label>
          <Input
            type="text"
            name="phoneBurnerLastCallOutcome"
            value={formData.phoneBurnerLastCallOutcome || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <div className="flex items-center space-x-2">
            <Checkbox
              id="reRunRoundRobin"
              checked={formData.reRunRoundRobin || false}
              onCheckedChange={(checked) => setFormData({ ...formData, reRunRoundRobin: checked })}
            />
            <Label htmlFor="reRunRoundRobin">Re-run round robin</Label>
          </div>
        </div>
        <div className="mb-3">
          <div className="flex items-center space-x-2 h-full">
            <Checkbox
              id="emailRoundRobinOwner"
              checked={formData.emailRoundRobinOwner || false}
              onCheckedChange={(checked) => setFormData({ ...formData, emailRoundRobinOwner: checked })}
            />
            <Label htmlFor="emailRoundRobinOwner">Email Round Robin Owner</Label>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <div className="flex items-center space-x-2 h-full">
            <Checkbox
              id="roundRobinProcessed"
              checked={formData.roundRobinProcessed || false}
              onCheckedChange={(checked) => setFormData({ ...formData, roundRobinProcessed: checked })}
            />
            <Label htmlFor="roundRobinProcessed">Round Robin Processed</Label>
          </div>
        </div>
        <div className="mb-3">
          <div className="flex items-center space-x-2">
            <Checkbox
              id="eligibleRoundRobinOwnerFound"
              checked={formData.eligibleRoundRobinOwnerFound || false}
              onCheckedChange={(checked) => setFormData({ ...formData, eligibleRoundRobinOwnerFound: checked })}
            />
            <Label htmlFor="eligibleRoundRobinOwnerFound">Eligible Round Robin Owner Found</Label>
          </div>
        </div>
        <div className="mb-3">
          {/* Empty */}
        </div>
      </div>
    </div>
  );
};

export default DealInformation;
