// client/app/src/views/demo/dealComponents/PolicyReview.vue
<template>
  <h5 class="main-heading mb-0">Policy Review & Renewal</h5>
  <div>
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Renewal Medical Requirement?</label>
        <select v-model="formData.medicalRequirement" class="form-select">
          <option
            v-for="(option, index) in renewal"
            :key="index"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Policy Review Comments</label>
        <textarea
          v-model="formData.reviewComments"
          class="form-control form-control-default"
          rows="1"
        ></textarea>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Policy Review Comments Updated On-</label>
        <input
          v-model="formData.commentsUpdatedOn"
          type="date"
          class="form-control form-control-default"
        />
      </div>
    </div>
    <div class="row mt-3">
      <!--Policy Renewal Date-->
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Policy Renewal Date</label>
        <input
          v-model="formData.policyRenewalDate"
          type="date"
          class="form-control"
        />
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Renewal Medical Confirmation Number</label>
        <input
          v-model="formData.confirmationNumber"
          type="text"
          class="form-control form-control-default"
        />
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <div>
          <label class="my-0 mx-2" for="applicationDate"
            >Renewal Medical Application Date & Time
          </label>
          <input
            type="datetime-local"
            class="form-control border"
            id="applicationDate"
            v-model="formData.applicationDate"
          />
        </div>
      </div>
    </div>
    <div class="row mt-3">
      <!--Reviewd Date and Time-->
      <div class="col-lg-4 col-md-4 col-sm-12">
        <div>
          <label class="my-0 mx-2" for="reviewedDate"
            >Reviewd Date and Time</label
          >
          <input
            type="datetime-local"
            class="form-control border"
            id="reviewedDate"
            v-model="formData.reviewedDate"
          />
        </div>
      </div>
      <!--Policy Expired Date-->
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Policy Expired On</label>
        <input
          v-model="formData.policyExpiredDate"
          type="date"
          class="form-control"
        />
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Policy Renewal Completed</label>
        <select v-model="formData.renewalCompleted" class="form-select">
          <option
            v-for="(option, index) in objectType"
            :key="index"
            :value="option"
          >
            {{ option }}
          </option>
        </select>
      </div>
    </div>
  </div>
  <div class="button-row d-flex justify-content-center mt-2 gap-4">
    <button
      class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev"
      type="button"
      @click="previousStep"
    >
      Prev
    </button>
    <button
      class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next"
      @click.prevent="nextStep"
      type="button"
    >
      Next
    </button>
  </div>
</template>

<script>
import {renewal,objectType} from "../utils/picklist.js";
export default {
  name: "InsuranceInquiryForm",
  props: {
    getPolicyReview: {
      type: Function,
      required: true,
    },
    PolicyReview: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      formData: { ...this.PolicyReview },
      objectType : { ...objectType },
      renewal : { ...renewal }
    };
  },
  watch: {
    PolicyReview: {
      handler(formData) {
        this.formData = { ...this.PolicyReview };
        console.log("this formData PolicyReview", formData);
      },
      immediate: true,
      deep: true,
    },
  },
  methods: {
    sendData() {
      this.getPolicyReview(this.formData);
    },
    nextStep() {
      this.$emit("next", this.formData);
    },
    previousStep() {
      this.$emit("previous");
    },
  },
};
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
</style>

// frontend/src/features/crm/pages/deals/dealFormComponents/PolicyReview.jsx
import React from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { renewal, objectType } from "../utils/picklist";

const PolicyReview = ({ formData, setFormData }) => {
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  return (
    <div className="policy-review">
      <h5 className="main-heading mb-4 ps-2">Review & Renewal</h5>
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">Medical Requirement</Label>
          <Select
            value={formData.medicalRequirement || ""}
            onValueChange={(value) => setFormData({ ...formData, medicalRequirement: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {objectType.map((opt) => (
                <SelectItem key={opt} value={opt}>
                  {opt}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Review Comments</Label>
          <Textarea
            name="reviewComments"
            value={formData.reviewComments || ""}
            onChange={handleChange}
            rows="3"
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Comments Updated On</Label>
          <Input
            type="date"
            name="commentsUpdatedOn"
            value={formData.commentsUpdatedOn || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Policy Renewal Date</Label>
          <Input
            type="date"
            name="policyRenewalDate"
            value={formData.policyRenewalDate || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Confirmation Number</Label>
          <Input
            type="text"
            name="confirmationNumber"
            value={formData.confirmationNumber || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Renewal Medical Application Date & Time</Label>
          <Input
            type="datetime-local"
            name="renewalMedicalApplicationDateTime"
            value={formData.renewalMedicalApplicationDateTime || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Reviewed Date</Label>
          <Input
            type="date"
            name="reviewedDate"
            value={formData.reviewedDate || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Policy Expired Date</Label>
          <Input
            type="date"
            name="policyExpiredDate"
            value={formData.policyExpiredDate || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Renewal Completed</Label>
          <Select
            value={formData.renewalCompleted || ""}
            onValueChange={(value) => setFormData({ ...formData, renewalCompleted: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {renewal.map((ren) => (
                <SelectItem key={ren} value={ren}>
                  {ren}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
    </div>
  );
};

export default PolicyReview;
