// frontend/src/features/crm/pages/advisor/leadAdvisorFormComponents/FestivalForm.jsx
import React, { useState, useEffect } from 'react';
import { religionOptions, festivalsOptions, religionFestivals, religions } from '../utils/picklist';
import Select from 'react-select';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { TrashIcon } from 'lucide-react';
import { Select as ShadcnSelect, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';



const FestivalForm = ({ formData, setFormData, isDisabled }) => {
  const [subform, setSubform] = useState([]);

  useEffect(() => {
    setSubform(formData.festivalsData || []);
  }, [formData]);

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubformChange = (index, field, value) => {
    const updated = [...subform];
    updated[index][field] = value;
    setSubform(updated);
  };

  const addRowToFestivalsTable = () => {
    setSubform(prev => [...prev, { festivalName: '', dateOfFestival: '' }]);
  };

  const deleteFestivalTableRow = (index) => {
    const updated = [...subform];
    updated.splice(index, 1);
    setSubform(updated);
  };

  const availableFestivals = () => {
    if (!formData.religion || formData.religion.length === 0) return [];
    return formData.religion.reduce((all, rel) => {
      const list = religionFestivals[rel] || [];
      return all.concat(list);
    }, []);
  };

  useEffect(() => {
    if (!formData.religion || formData.religion.length === 0) {
      setFormData(prev => ({ ...prev, festival: [] }));
      return;
    }
    const allFestivals = formData.religion.reduce((acc, religion) => {
      const festivals = religionFestivals[religion] || [];
      return acc.concat(festivals);
    }, []);
    setFormData(prev => ({ ...prev, festival: allFestivals }));
  }, [formData.religion]);



  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Ethnicity</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Religion</label>
              <Select
                isMulti
                options={religions.map(rel => ({ value: rel, label: rel }))}
                value={formData.religion.map(rel => ({ value: rel, label: rel }))}
                onChange={(selected) => setFormData(prev => ({ ...prev, religion: selected.map(s => s.value) }))}
                placeholder="Select Religion"
                className="custom-vselect"
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Celebrated Festivals</label>
              <Select
                isMulti
                options={availableFestivals().map(fest => ({ value: fest, label: fest }))}
                value={formData.festival.map(fest => ({ value: fest, label: fest }))}
                onChange={(selected) => setFormData(prev => ({ ...prev, festival: selected.map(s => s.value) }))}
                placeholder="Select Celebrated Festivals"
                className="custom-vselect"
              />
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Important Festivals Dates</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="w-full overflow-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>#</TableHead>
                  <TableHead>Actions</TableHead>
                  <TableHead>Festival Name</TableHead>
                  <TableHead>Date On Celebrated</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {subform.map((parent, index) => (
                  <TableRow key={index}>
                    <TableCell className="text-center">{index + 1}</TableCell>
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => deleteFestivalTableRow(index)}
                        className="text-red-500 hover:text-red-700"
                      >
                        <TrashIcon className="h-4 w-4" />
                      </Button>
                    </TableCell>
                    <TableCell>
                      <div className="choices" data-type="select-one" tabIndex="0" role="listbox" aria-haspopup="true" aria-expanded="false">
                        <div className="select-box">
                          <select
                            value={parent.festivalName || ''}
                            onChange={(e) => handleSubformChange(index, 'festivalName', e.target.value)}
                            className="multisteps-form__select form-control choices__input border p-2 rounded-md"
                            name="choices-state"
                          >
                            <option value="">Select Festival</option>
                            {festivalsOptions.map((option, idx) => (
                              <option key={idx} value={option}>
                                {option}
                              </option>
                            ))}
                          </select>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell>
                      <Input
                        value={parent.dateOfFestival || ''}
                        onChange={(e) => handleSubformChange(index, 'dateOfFestival', e.target.value)}
                        type="date"
                        autoComplete="off"
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <Button
            onClick={addRowToFestivalsTable}
            className="mt-4"
          >
            Add Row
          </Button>
        </CardContent>
      </Card>

      <div className="flex justify-center gap-4" style={{ marginBottom: '200px' }}>
        <Button
          variant="outline"
          onClick={handlePrevious}
        >
          Prev
        </Button>
        <Button
          onClick={handleNext}
        >
          Next
        </Button>
      </div>
    </div>
  );
};

export default FestivalForm;

// client/app/src/views/deals/LifeCriticalInsurance/LifeCriticalInsuranceComponents/FestivalForm.vue
<template>
  <div class="ps-2">
    <h5 class="main-heading mt-2">Ethnicity</h5>
    <div class="row">
      <div class="col-lg-4 col-sm-6 mt-2 mt-sm-0">
        <label class="my-0">Religion</label>
        <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true" aria-expanded="false">
          <div class="select-box">
            <select v-model="formData.religion" class="multisteps-form__select form-control choices__input" name="choices-state">
              <option v-for="(option, index) in religionOptions" :key="index" :value="option">
                {{ option }}
              </option>
            </select>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-sm-6 mt-2 mt-sm-0">
        <label class="my-0">Celebrated Festivals</label>
        <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true" aria-expanded="false">
          <div class="select-box">
            <select v-model="formData.celebratedFestivals" class="multisteps-form__select form-control choices__input" name="choices-state">
              <option v-for="(option, index) in celebratedFestivalsOptions" :key="index" :value="option">
                {{ option }}
              </option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <h5 class="main-heading mt-2">Important Festivals Dates</h5>
    <div style="width: 100%; overflow: scroll">
      <table class="table border table-responsive subform">
        <thead class="table subform-table-head text-white">
          <tr>
            <th>#</th>
            <th>Actions</th>
            <th>Festival Name</th>
            <th>Date On Celebrated</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <tr v-for="(parent, index) in festivalsData" :key="index">
            <td class="m-auto">{{ index + 1 }}</td>
            <td>
              <a @click.prevent="deleteFestivalTableRow(index)" href="javascript:;" data-bs-toggle="tooltip" data-bs-original-title="Delete product">
                <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true" aria-expanded="false">
                <div class="select-box">
                  <select v-model="parent.festivalName" class="multisteps-form__select form-control choices__input" name="choices-state">
                    <option v-for="(option, index) in festivals" :key="index" :value="option">
                      {{ option }}
                    </option>
                  </select>
                </div>
              </div>
            </td>
            <td>
              <input v-model="parent.dateOfFestival" type="date" class="form-control form-control-default" autocomplete="off">
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <button class="btn mb-0 btn-color btn-md null null" type="button" @click.prevent="addRowToFestivalsTable">
      Add Row
    </button>

    <div class="button-row d-flex justify-content-center mt-4 gap-4 space">
      <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" @click="previousSteps" type="button">Prev</button>
      <button class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" @click.prevent="nextStep" type="button">Next</button>
    </div>
  </div>
</template>

<script>
import {religionOptions , festivalsOptions, celebratedFestivalsOptions} from "../../utils/picklist.js";

export default {
  name: "HolidayDateForm",
  props: {
    FestivalForm:{
      type: Object,
      required: true
    }
  },
  data() {
    return {
      formData: {...this.FestivalForm},
      festivalsData:[],
      religionOptions: {...religionOptions},
      festivals: {...festivalsOptions},
      celebratedFestivalsOptions: {...celebratedFestivalsOptions},
    };
  },
  watch: {
    FestivalForm:{
      handler(formData){
        this.formData = {...this.FestivalForm}
        this.festivalsData = this.FestivalForm.festivalsData || [];

        console.log("FormData lead FestivalForm: ", formData)
      },
      immediate: true,
      deep: true
    }
  },
  methods: {
    nextStep(){
      this.$emit('next', {...this.formData,festivalsData: this.festivalsData});
    },
    previousSteps(){
      this.$emit('previous', {...this.formData,festivalsData: this.festivalsData});
    },
    addRowToFestivalsTable() {
      this.festivalsData.push({
        festivalName: "",
        dateOfFestival: ""
      });
    },
    deleteFestivalTableRow(index) {
      this.festivalsData.splice(index, 1);
    }
  }
};
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
@media screen and (max-width:500px) {
  .space{
    margin-bottom:100px;
  }
}
</style>
