// frontend/src/features/crm/pages/deals/dealFormComponents/DealTrustee.jsx
import React, { useState, useEffect } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { objectType } from "../utils/picklist";

const DealTrustee = ({ formData, setFormData }) => {
  const [trustees, setTrustees] = useState(formData.trustees || []);

  useEffect(() => {
    setFormData({ ...formData, trustees });
  }, [trustees]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleTrusteeChange = (index, field, value) => {
    const updatedTrustees = [...trustees];
    updatedTrustees[index] = { ...updatedTrustees[index], [field]: value };
    setTrustees(updatedTrustees);
  };

  const addRow = () => {
    setTrustees([...trustees, {
      nameOfTrustees: "",
      nameOfBeneficiaryForTrustee: "",
      relationshipWithBeneficiaryForTrustee: "",
      trusteePhone: "",
      trusteeEmail: ""
    }]);
  };

  const deleteRow = (index) => {
    const updatedTrustees = trustees.filter((_, i) => i !== index);
    setTrustees(updatedTrustees);
  };

  return (
    <div className="deal-trustee">
      <h5 className="main-heading mb-4 ps-2">Trustee</h5>
      <div className="grid grid-cols-3 gap-4 ps-2 mb-3">
        <div className="mb-3">
          <Label className="my-0">Are there Trustees for this Policy?</Label>
          <Select
            value={formData.areThereTrusteesforThisPolicy || ""}
            onValueChange={(value) => setFormData({ ...formData, areThereTrusteesforThisPolicy: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {objectType.map((opt) => (
                <SelectItem key={opt} value={opt}>
                  {opt}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Trust Documents Received and Uploaded</Label>
          <Select
            value={formData.trustDocumentsReceivedAndUploaded || ""}
            onValueChange={(value) => setFormData({ ...formData, trustDocumentsReceivedAndUploaded: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {objectType.map((opt) => (
                <SelectItem key={opt} value={opt}>
                  {opt}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Trust Dissolution Date</Label>
          <Input
            type="date"
            name="trustDissolutionDate"
            value={formData.trustDissolutionDate || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Application On</Label>
          <Input
            type="date"
            name="applicationOn"
            value={formData.applicationOn || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
        <div className="mb-3">
          <Label className="my-0">Number of Trustees</Label>
          <Input
            type="number"
            name="numberOfTrustees"
            value={formData.numberOfTrustees || ""}
            onChange={handleChange}
            className="w-full"
          />
        </div>
      </div>
      <div style={{ width: "100%", overflow: "scroll" }}>
        <Table className="border table-responsive subform">
          <TableHeader className="subform-table-head text-white">
            <TableRow>
              <TableHead>#</TableHead>
              <TableHead>Actions</TableHead>
              <TableHead>Name of Trustees</TableHead>
              <TableHead>Name of Beneficiary for Trustee</TableHead>
              <TableHead>Relationship with Beneficiary for Trustee</TableHead>
              <TableHead>Trustee Phone</TableHead>
              <TableHead>Trustee Email</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="table-group-divider">
            {trustees.map((trustee, index) => (
              <TableRow key={index}>
                <TableCell className="m-auto">{index + 1}</TableCell>
                <TableCell>
                  <Button
                    type="button"
                    onClick={() => deleteRow(index)}
                    variant="destructive"
                    size="sm"
                  >
                    <i className="fas fa-trash"></i>
                  </Button>
                </TableCell>
                <TableCell>
                  <Input
                    type="text"
                    value={trustee.nameOfTrustees || ""}
                    onChange={(e) => handleTrusteeChange(index, "nameOfTrustees", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="text"
                    value={trustee.nameOfBeneficiaryForTrustee || ""}
                    onChange={(e) => handleTrusteeChange(index, "nameOfBeneficiaryForTrustee", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="text"
                    value={trustee.relationshipWithBeneficiaryForTrustee || ""}
                    onChange={(e) => handleTrusteeChange(index, "relationshipWithBeneficiaryForTrustee", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="tel"
                    value={trustee.trusteePhone || ""}
                    onChange={(e) => handleTrusteeChange(index, "trusteePhone", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="email"
                    value={trustee.trusteeEmail || ""}
                    onChange={(e) => handleTrusteeChange(index, "trusteeEmail", e.target.value)}
                  />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <Button type="button" onClick={addRow} className="mb-0 btn-color btn-md">
        Add Row
      </Button>
    </div>
  );
};

export default DealTrustee;

// client/app/src/views/demo/dealComponents/DealTrustee.vue
<template>
  <div>
    <h5 class="main-heading mt-2">Deal Trustee</h5>
    <div class="row mb-2">
      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Are there Trustees for this Policy?</label>
        <div
          class="choices"
          data-type="select-one"
          tabindex="0"
          role="listbox"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <div class="select-box">
            <select
              v-model="formData.areThereTrusteesforThisPolicy"
              class="multisteps-form__select form-control choices__input"
              name="choices-state"
            >
              <option
                v-for="(option, index) in objectType"
                :key="index"
                :value="option"
              >
                {{ option }}
              </option>
            </select>
          </div>
        </div>
      </div>
      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Trust Documents Received and Uploaded </label>
        <div
          class="choices"
          data-type="select-one"
          tabindex="0"
          role="listbox"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <div class="select-box">
            <select
              v-model="formData.trustDocumentsReceivedAndUploaded"
              class="multisteps-form__select form-control choices__input"
              name="choices-state"
            >
              <option
                v-for="(option, index) in objectType"
                :key="index"
                :value="option"
              >
                {{ option }}
              </option>
            </select>
          </div>
        </div>
      </div>

      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Trust Dissolution Date</label>
        <div>
          <input
            class="form-control"
            type="date"
            v-model="formData.trustDissolutionDate"
          />
        </div>
      </div>
      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Application Initiated On</label>
        <div>
          <input
            class="form-control"
            type="date"
            v-model="formData.applicationOn"
          />
        </div>
      </div>
      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Number of trustees</label>
        <div>
          <input
            class="form-control"
            type="text"
            v-model="formData.numberOfTrustees"
          />
        </div>
      </div>
    </div>
    <div style="width: 100%; overflow: scroll">
      <table class="table border table-responsive subform">
        <thead class="table subform-table-head text-white">
          <tr>
            <th>#</th>
            <th>Actions</th>
            <th>Name of Trustee</th>
            <th>Name of Beneficiary for Trustee</th>
            <th>Relationship with Beneficiary for Trustee</th>
            <th>Insured Phone</th>
            <th>Insured Email</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <tr v-for="(parent, index) in subform" :key="index">
            <td class="m-auto">{{ index + 1 }}</td>
            <td>
              <a
                @click.prevent="deleteLeadsRow(index)"
                href="javascript:;"
                data-bs-toggle="tooltip"
                data-bs-original-title="Delete product"
              >
                <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <input
                v-model="parent.name"
                type="text"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
            <td>
              <input
                v-model="parent.nameOfBeneficiary"
                type="text"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
            <td>
              <input
                v-model="parent.relationship"
                type="text"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
            <td>
              <input
                v-model="parent.phone"
                type="tel"
                class="form-control form-control-default"
                autocomplete="off"
                pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
              />
            </td>
            <td>
              <input
                v-model="parent.email"
                type="email"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <button
      class="btn mb-0 btn-color btn-md"
      type="button"
      @click.prevent="addRowTodealTrusteeTable"
    >
      Add Row
    </button>
    <div class="button-row d-flex justify-content-center mt-2 gap-4">
      <button
        class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev"
        type="button"
        @click="previousStep"
      >
        Prev
      </button>
      <button
        class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next"
        @click.prevent="nextStep"
        type="button"
      >
        Next
      </button>
    </div>
  </div>
</template>

<script>
import { objectType } from "../utils/picklist.js";
export default {
  name: "DealTrustee", // Make sure this name matches your component's intended use
  props: {
    DealTrustee: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
        subform: [],
      formData: { ...this.DealTrustee },
      objectType: { ...objectType },
    };
  },
  watch: {
    DealTrustee: {
      handler() {
        this.formData = { ...this.DealTrustee };
        this.subform = this.DealTrustee.trustees || [];
      },
      immediate: true,
      deep: true,
    },
  },
  methods: {
    addRowTodealTrusteeTable() {
        console.log("Adding new row to trusteeData");
      this.subform.push({}); 
      // this.subform.push({
      //   name: "",
      //   // nameOfBeneficiary: "",
      //   // relationship: "",
      //   // phone: "",
      //   // email: "",
      // });
    },
    deleteLeadsRow(index) {
      this.subform.splice(index, 1);
    },
    nextStep() {
      this.$emit("next",{ ...this.formData, trustee: this.subform });
    },
    previousStep() {
      this.$emit("previous");
    },
  },
};
</script>
<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
</style>
