// frontend/src/features/crm/pages/deals/dealFormComponents/DealOwnership.jsx
import React, { useState, useEffect } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { objectType } from "../utils/picklist";

const DealOwnership = ({ formData, setFormData }) => {
  const [dealOwnership, setDealOwnership] = useState(formData.dealOwnership || []);

  useEffect(() => {
    setFormData({ ...formData, dealOwnership });
  }, [dealOwnership]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleOwnershipChange = (index, field, value) => {
    const updatedOwnership = [...dealOwnership];
    updatedOwnership[index] = { ...updatedOwnership[index], [field]: value };
    setDealOwnership(updatedOwnership);
  };

  const addRow = () => {
    setDealOwnership([...dealOwnership, { numberOfInsured: "", insuredName: "", insuredPhone: "", insuredEmail: "" }]);
  };

  const deleteRow = (index) => {
    const updatedOwnership = dealOwnership.filter((_, i) => i !== index);
    setDealOwnership(updatedOwnership);
  };

  return (
    <div className="deal-ownership">
      <div className="grid grid-cols-3 gap-4 ps-2">
        <div className="mb-3">
          <Label className="my-0">Is Client the Insured?</Label>
          <Select
            value={formData.isClientTheInsured || ""}
            onValueChange={(value) => setFormData({ ...formData, isClientTheInsured: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {objectType.map((opt) => (
                <SelectItem key={opt} value={opt}>
                  {opt}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="mb-3">
          <Label className="my-0">Are there Multiple Insured for this Policy?</Label>
          <Select
            value={formData.areThereMultipleInsuredForThisPolicy || ""}
            onValueChange={(value) => setFormData({ ...formData, areThereMultipleInsuredForThisPolicy: value })}
          >
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {objectType.map((opt) => (
                <SelectItem key={opt} value={opt}>
                  {opt}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
      <h5 className="main-heading mb-4 ps-2">Deal Owner</h5>
      <div style={{ width: "100%", overflow: "scroll" }}>
        <Table className="border table-responsive subform">
          <TableHeader className="subform-table-head text-white">
            <TableRow>
              <TableHead>#</TableHead>
              <TableHead>Actions</TableHead>
              <TableHead>Number of Insured</TableHead>
              <TableHead>Insured Name</TableHead>
              <TableHead>Insured Phone</TableHead>
              <TableHead>Insured Email</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="table-group-divider">
            {dealOwnership.map((ownership, index) => (
              <TableRow key={index}>
                <TableCell className="m-auto">{index + 1}</TableCell>
                <TableCell>
                  <Button
                    type="button"
                    onClick={() => deleteRow(index)}
                    variant="destructive"
                    size="sm"
                  >
                    <i className="fas fa-trash"></i>
                  </Button>
                </TableCell>
                <TableCell>
                  <Input
                    type="number"
                    value={ownership.numberOfInsured || ""}
                    onChange={(e) => handleOwnershipChange(index, "numberOfInsured", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="text"
                    value={ownership.insuredName || ""}
                    onChange={(e) => handleOwnershipChange(index, "insuredName", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="tel"
                    value={ownership.insuredPhone || ""}
                    onChange={(e) => handleOwnershipChange(index, "insuredPhone", e.target.value)}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="email"
                    value={ownership.insuredEmail || ""}
                    onChange={(e) => handleOwnershipChange(index, "insuredEmail", e.target.value)}
                  />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <Button type="button" onClick={addRow} className="mb-0 btn-color btn-md">
        Add Row
      </Button>
    </div>
  );
};

export default DealOwnership;

// client/app/src/views/demo/dealComponents/DealOwnership.vue
<template>
  <div>
    <div class="row">
      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Is Client the Insured?</label>
        <div
          class="choices"
          data-type="select-one"
          tabindex="0"
          role="listbox"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <div class="select-box">
            <select
              v-model="formData.isClientTheInsured"
              class="multisteps-form__select form-control choices__input"
              name="choices-state"
            >
              <option
                v-for="(option, index) in objectType"
                :key="index"
                :value="option"
                :selected="option === '-None-'"
              >
                {{ option }}
              </option>
            </select>
          </div>
        </div>
      </div>
      <div class="col-4 col-sm-4 mt-2 mt-sm-0">
        <label class="my-0">Are there multiple Insured for this Policy? </label>
        <div
          class="choices"
          data-type="select-one"
          tabindex="0"
          role="listbox"
          aria-haspopup="true"
          aria-expanded="false"
        >
          <div class="select-box">
            <select
              v-model="formData.areThereMultipleInsuredForThisPolicy"
              class="multisteps-form__select form-control choices__input"
              name="choices-state"
            >
              <option
                v-for="(option, index) in objectType"
                :key="index"
                :value="option"
                :selected="option === '-None-'"
              >
                {{ option }}
              </option>
            </select>
          </div>
        </div>
      </div>
    </div>
    <h5 class="main-heading mt-2">Deal Owner</h5>
    <div style="width: 100%; overflow: scroll">
      <table class="table border table-responsive subform">
        <thead class="table subform-table-head text-white">
          <tr>
            <th>#</th>
            <th>Actions</th>
            <th>Number of Insured</th>
            <th>Insured Name</th>
            <th>Insured Phone</th>
            <th>Insured Email</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <tr v-for="(parent, index) in subForm" :key="index">
            <td class="m-auto">{{ index + 1 }}</td>
            <td>
              <a
                @click.prevent="deleteLeadsRow(index)"
                href="javascript:;"
                data-bs-toggle="tooltip"
                data-bs-original-title="Delete product"
              >
                <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <input
                v-model="parent.numberOfInsured"
                type="number"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
            <td>
              <input
                v-model="parent.insuredName"
                type="text"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
            <td>
              <input
                v-model="parent.insuredPhone"
                type="tel"
                class="form-control form-control-default"
                autocomplete="off"
                pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
              />
            </td>
            <td>
              <input
                v-model="parent.insuredEmail"
                type="email"
                class="form-control form-control-default"
                autocomplete="off"
              />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <button
      class="btn mb-0 btn-color btn-md"
      type="button"
      @click.prevent="addRowTodealDataTable"
    >
      Add Row
    </button>
  </div>
  <div class="button-row d-flex justify-content-center mt-2 gap-4">
    <button
      class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev"
      type="button"
      @click="previousStep"
    >
      Prev
    </button>
    <button
      class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next"
      @click.prevent="nextStep"
      type="button"
    >
      Next
    </button>
  </div>
</template>

<script>
import {objectType} from "../utils/picklist.js";
// import { ref } from "vue";
export default {
  name: "LeadManagementHistory",
   props: {
    DealOwnership: {
      type: Object,
      default: () => ({}),
    },
  },
  data() {
    return {
      formData: { ...this.DealOwnership },
      objectType: { ...objectType },
      subForm: [],
    };
  },
  watch: {
    DealOwnership: {
      handler() {
        console.log("<<<<<<<<<<<INSERT THE WATCH FOR DEALOWNERSHIP>>>>>>>>>>>>>>>>>>>>>>>>>")
        this.formData = { ...this.DealOwnership };
        this.subForm = this.DealOwnership.dealOwnership || [];
        console.log("<<<<<<<<< == this formData deal DealOwnership ==>>>>>>>>>", this.formData);
      },
      immediate: true,
      deep: true,
    },
  },
  methods: {
    addRowTodealDataTable() {
      this.subForm.push({
        numberOfInsured: "",
        insuredName: "",
        insuredPhone: "",
        insuredEmail: "",
      });
    },
    deleteLeadsRow(index) {
      this.subForm.splice(index, 1);
    },
    nextStep() {
      this.$emit("next", { ...this.formData, dealOwnership: this.subForm });  
    },
    previousStep() {
      this.$emit("previous");
    },
  },
};
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
</style>
