// client/app/src/views/Policies/investment/component/Beneficiary.vue
<template>
    <div style="margin-bottom:80px;">
        <h5 class="main-heading mt-2 ps-2">Deal Beneficiaries</h5>
        <div class="row mb-2 ps-2">
            <div class="col-lg-4 col-sm-6 mt-2 mt-md-4 mt-sm-0">
                <label class="my-0">Is Client a Beneficiary?</label>
                <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
                    aria-expanded="false">
                    <div class="select-box">
                        <select v-model="formData.isClientABeneficiary"
                            class="multisteps-form__select form-control choices__input" name="choices-state">
                            <option v-for="(option, index) in isClientaBeneficiary" :key="index" :value="option">
                                {{ option }}
                            </option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 mt-2 mt-md-4  mt-sm-0">
                <label class="my-0">Are there Multiple Beneficiaries ?</label>
                <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
                    aria-expanded="false">
                    <div class="select-box">
                        <select v-model="formData.arethereMultipleBeneficiaries"
                            class="multisteps-form__select form-control choices__input" name="choices-state">
                            <option v-for="(option, index) in isClientaBeneficiary" :key="index" :value="option">
                                {{ option }}
                            </option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 mt-2 mt-md-4 mt-sm-0">
                <label class="my-0">Beneficiary Gender</label>
                <div class="select-box">
                    <select v-model="formData.beneficiaryGender" class="form-control">
                        <option value="" disabled selected>Select Gender</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                        <option value="Unkown">Unkown</option>
                    </select>
                </div>
            </div>
            <div v-if="formData.layout === 'RRSP'" class="col-4 col-sm-4 mt-2 mt-sm-0">
                <label class="my-0">Beneficiary Type</label>
                <div class="select-box">
                    <select v-model="formData.beneficiaryType" class="form-control">
                        <option value="" disabled selected>Beneficiary Type</option>
                        <option value="None">None</option>
                        <option value="Revocable">Revocable</option>
                        <option value="Irrevocable">Irrevocable</option>
                    </select>
                </div>
            </div>

            <div class="col-lg-4 col-md-6 col-sm-6 mt-md-4">
                <label class="my-0">Number of Beneficiaries</label>
                <input v-model="formData.numberofBeneficiaries" type="text" class="form-control form-control-default" />
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mt-lg-4">
                <label class="my-0">Relation to Primary Annuitant</label>
                <input v-model="formData.relationtoPrimaryAnnuitant" type="text"
                    class="form-control form-control-default" />
            </div>
        </div>
        <div style="width: 100%; overflow: scroll">
            <table class="table border table-responsive subform">
                <thead class="table subform-table-head text-white">
                    <tr>
                        <th>#</th>
                        <th>Actions</th>
                        <th>Beneficiary Name</th>
                        <th>Relationship to Primary Beneficiary</th>
                        <th>Beneficiary Phone</th>
                        <th>Beneficiary Email</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    <tr v-for="(beneficiary, index) in Beneficiary" :key="index">
                        <td class="m-auto">{{ index + 1 }}</td>
                        <td>
                            <a @click.prevent="deleteLeadsRow(index)" href="javascript:;" data-bs-toggle="tooltip"
                                data-bs-original-title="Delete product">
                                <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <input v-model="beneficiary.name" type="text" class="form-control form-control-default"
                                autocomplete="off">
                        </td>
                        <td>
                            <input v-model="beneficiary.relationship" type="text"
                                class="form-control form-control-default" autocomplete="off">
                        </td>
                        <td>
                            <!-- <input v-model="beneficiary.phone" type="tel" class="form-control form-control-default"
                                autocomplete="off" pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"> -->

                            <VueTelInput v-model="beneficiary.phone"  :defaultCountry="'CA'"
                                :preferredCountries="['CA', 'US', 'IN', 'GB']" :enableAutoCountrySelect="true"
                                :mode="'international'" :inputOptions="{
                                    placeholder: '+1 (XXX) XXX-XXXX',
                                    inputmode: 'tel',
                                    maxlength: 16,            // '+' + 15 digits (E.164)
                                    onInput: handleTelInput   // live sanitize
                                }" id="mobile" />
                            <span v-if="errors.mobile" class="text-danger">{{ errors.mobile }}</span>

                        </td>
                        <td>
                            <input v-model="beneficiary.email" type="email" class="form-control form-control-default"
                                autocomplete="off">
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <button class="btn mb-0 btn-color btn-md" type="button" @click.prevent="addRowTodealbeneficiaryTable">
            Add Row
        </button>

        <div class="button-row d-flex justify-content-center mt-4 gap-4">
            <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" type="button"
                @click="prevStep">Prev</button>
            <button v-if="!id" class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" type="button"
                @click.prevent="nextStep">
                Submit
            </button>
        </div>
    </div>
</template>
<style></style>
<script>
import { clientFirstPolicyOptions } from "../../utils/picklist";
import { VueTelInput } from 'vue-tel-input'
import 'vue-tel-input/dist/vue-tel-input.css'
export default {
    components: {
    VueTelInput
  },

    props: {
        services: {
            type: Object,
            required: true
        }
    },
    watch: {
        services: {
            handler() {
                this.formData = { ...this.services };
                this.isClientaBeneficiary = { ...clientFirstPolicyOptions };
                this.Beneficiary = this.services.Beneficiary || [];

            },
            deep: true,
            immediate: true,
        }
    },
    data() {
        return {
            Beneficiary: [],
            errors: {},
            formData: { ...this.services }
        }
    },
    methods: {
        handleTelInput(e) {
      const raw = e?.target?.value ?? '';
      // keep leading +, strip everything else non-digit
      let cleaned = raw.replace(/(?!^)\+/g, '');       // remove extra '+' if any
      cleaned = cleaned.replace(/[^+\d]/g, '');        // only '+' and digits
      // limit to '+' + 15 digits
      const plus = cleaned.startsWith('+') ? '+' : '';
      const digits = cleaned.replace(/\D/g, '').slice(0, 15);
      cleaned = plus + digits;
      e.target.value = cleaned;
      this.formData.mobile = cleaned;
      // clear error as user fixes
      if (this.errors.mobile) delete this.errors.mobile;
    },
    nextStep() {
  this.errors = validateMandatoryFields(this.formData, mandatory);

  const mobile = (this.formData.mobile || "").replace(/\s|-/g, "");
  
  if (mobile) {
    if (!mobile.startsWith("+")) {
      this.errors.mobile = "Country code is required (e.g. +1...)";
    } else if (/^\+1/.test(mobile) && !/^\+1\d{10}$/.test(mobile)) {
      this.errors.mobile = "Canadian number must be +1 followed by 10 digits";
    } else if (!/^\+\d{8,15}$/.test(mobile)) {
      this.errors.mobile = "Phone must be in international format (e.g. +1234567890)";
    }
  }
},

        addRowTodealbeneficiaryTable() {
            this.Beneficiary.push({
                email: '',
                phone: '',
                relationship: '',
                name: '',
            });
        },
        deleteLeadsRow(index) {
            this.Beneficiary.splice(index, 1);
        },
        nextStep() {
            this.$emit('next', { ...this.formData, Beneficiary: this.Beneficiary });
        },
        prevStep() {
            this.$emit('previous', { ...this.formData, Beneficiary: this.Beneficiary });
        },
    }
}
</script>

// frontend/src/features/Policy/investment/components/Beneficiary.jsx
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import PhoneInput from 'react-phone-number-input';
import 'react-phone-number-input/style.css';
import {
  clientFirstPolicyOptions,
} from "@/utils/picklist";

const Beneficiary = ({ formData, setFormData, onNext, onPrev }) => {
  const [beneficiaries, setBeneficiaries] = useState(formData.Beneficiary || []);

  const handleChange = (field, value) => {
    setFormData({ ...formData, [field]: value });
  };

  const handleNext = () => {
    setFormData({ ...formData, Beneficiary: beneficiaries });
    onNext();
  };

  const handlePrev = () => {
    onPrev();
  };

  const addRow = () => {
    setBeneficiaries([...beneficiaries, {
      name: '',
      relationship: '',
      phone: '',
      email: '',
    }]);
  };

  const deleteRow = (index) => {
    const newBeneficiaries = beneficiaries.filter((_, i) => i !== index);
    setBeneficiaries(newBeneficiaries);
  };

  const updateBeneficiary = (index, field, value) => {
    const newBeneficiaries = [...beneficiaries];
    newBeneficiaries[index][field] = value;
    setBeneficiaries(newBeneficiaries);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Deal Beneficiaries</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
            <div className="lg:col-span-4 sm:col-span-6">
              <Label className="mb-2">Is Client a Beneficiary?</Label>
              <Select value={formData.isClientABeneficiary} onValueChange={(value) => handleChange("isClientABeneficiary", value)}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {clientFirstPolicyOptions.map((option) => (
                    <SelectItem key={option} value={option}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="lg:col-span-4 sm:col-span-6">
              <Label className="mb-2">Are there Multiple Beneficiaries?</Label>
              <Select value={formData.arethereMultipleBeneficiaries} onValueChange={(value) => handleChange("arethereMultipleBeneficiaries", value)}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {clientFirstPolicyOptions.map((option) => (
                    <SelectItem key={option} value={option}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="lg:col-span-4 sm:col-span-6">
              <Label className="mb-2">Beneficiary Gender</Label>
              <Select value={formData.beneficiaryGender} onValueChange={(value) => handleChange("beneficiaryGender", value)}>
                <SelectTrigger className="w-full">
                  <SelectValue placeholder="Select Gender" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Male">Male</SelectItem>
                  <SelectItem value="Female">Female</SelectItem>
                  <SelectItem value="Unknown">Unknown</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {formData.layout === 'RRSP' && (
              <div className="lg:col-span-4 sm:col-span-6">
                <Label className="mb-2">Beneficiary Type</Label>
                <Select value={formData.beneficiaryType} onValueChange={(value) => handleChange("beneficiaryType", value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Beneficiary Type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="None">None</SelectItem>
                    <SelectItem value="Revocable">Revocable</SelectItem>
                    <SelectItem value="Irrevocable">Irrevocable</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
            <div className="lg:col-span-4 sm:col-span-6">
              <Label className="mb-2">Number of Beneficiaries</Label>
              <Input
                value={formData.numberofBeneficiaries || ""}
                onChange={(e) => handleChange("numberofBeneficiaries", e.target.value)}
              />
            </div>
            <div className="lg:col-span-4 sm:col-span-6">
              <Label className="mb-2">Relation to Primary Annuitant</Label>
              <Input
                value={formData.relationtoPrimaryAnnuitant || ""}
                onChange={(e) => handleChange("relationtoPrimaryAnnuitant", e.target.value)}
              />
            </div>
          </div>

          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>#</TableHead>
                  <TableHead>Actions</TableHead>
                  <TableHead>Beneficiary Name</TableHead>
                  <TableHead>Relationship to Primary Beneficiary</TableHead>
                  <TableHead>Beneficiary Phone</TableHead>
                  <TableHead>Beneficiary Email</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {beneficiaries.map((beneficiary, index) => (
                  <TableRow key={index}>
                    <TableCell>{index + 1}</TableCell>
                    <TableCell>
                      <Button
                        variant="destructive"
                        size="sm"
                        onClick={() => deleteRow(index)}
                      >
                        Delete
                      </Button>
                    </TableCell>
                    <TableCell>
                      <Input
                        value={beneficiary.name || ""}
                        onChange={(e) => updateBeneficiary(index, 'name', e.target.value)}
                      />
                    </TableCell>
                    <TableCell>
                      <Input
                        value={beneficiary.relationship || ""}
                        onChange={(e) => updateBeneficiary(index, 'relationship', e.target.value)}
                      />
                    </TableCell>
                    <TableCell>
                      <div className="border rounded-lg p-1.5">
                        <PhoneInput
                          value={beneficiary.phone || ""}
                          onChange={(value) => updateBeneficiary(index, 'phone', value)}
                          defaultCountry="CA"
                          international={true}
                          withCountryCallingCode={true}
                          placeholder="+1 (XXX) XXX-XXXX"
                          maxLength={16}
                        />
                      </div>
                    </TableCell>
                    <TableCell>
                      <Input
                        type="email"
                        value={beneficiary.email || ""}
                        onChange={(e) => updateBeneficiary(index, 'email', e.target.value)}
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <Button onClick={addRow} className="mt-4">
            Add Row
          </Button>
        </CardContent>
      </Card>

      <div className="flex justify-center gap-4">
        <Button onClick={handlePrev} variant="outline" className="px-6 py-2">
          Prev
        </Button>
        <Button onClick={handleNext} className="px-6 py-2">
          Submit
        </Button>
      </div>
    </div>
  );
};

export default Beneficiary;
