// frontend/src/features/crm/pages/advisor/leadAdvisorFormComponents/LeadInformation.jsx
import React, { useState, useEffect } from "react";
import { FormCard, FormField } from "@/components/custom/CustomFormComponents";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import validateMandatoryFields from "../utils/validate";
import {
  insuranceLeadSourceOptions,
  leadStatusOption,
  genderOption,
  objectType,
  additionalContactInformationOption,
  understandingOfInsuranceOption,
  citizenshipStatusOption,
  preferredContactTimeOption,
  preferredContactMethodOption,
  referredByOptions,
  currency,
} from "../utils/picklist";
import { getStatusColor } from "../utils/statusColorMap";
import SelectColorCode from "@/components/SelectColorCode";

const LeadInformation = ({
  onNext,
  LeadInformation: leadInfo,
  owners,
  adviosers,
  location,
  isDisabled = false,
}) => {
  const [formData, setFormData] = useState({ ...leadInfo });
  const [errors, setErrors] = useState({});

  useEffect(() => {
    setFormData({ ...leadInfo });
  }, [leadInfo]);

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleNext = () => {
    const validationErrors = validateMandatoryFields(formData, [
      { id: "insuranceLeadOwner", fieldName: "Insurance Lead Owner" },
      { id: "lastName", fieldName: "Last Name" },
    ]);
    setErrors(validationErrors);
    if (Object.keys(validationErrors).length === 0) {
      onNext(formData);
    }
  };

  return (
    <div>
      <FormCard title="Personal Details">
        {/* Row 1 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Insurance Lead Owner *">
            <Select
              value={formData.insuranceLeadOwner || ""}
              onValueChange={(value) =>
                handleInputChange("insuranceLeadOwner", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Owner" />
              </SelectTrigger>
              <SelectContent>
                {owners?.map((user) => (
                  <SelectItem key={user.ROWID} value={user.ROWID}>
                    {user.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.insuranceLeadOwner && (
              <span className="text-red-500 text-sm">
                {errors.insuranceLeadOwner}
              </span>
            )}
          </FormField>
          <FormField label="Insurance Lead Source">
            <Select
              value={formData.insuranceLeadSource || ""}
              onValueChange={(value) =>
                handleInputChange("insuranceLeadSource", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Source" />
              </SelectTrigger>
              <SelectContent>
                {insuranceLeadSourceOptions.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="First Name">
            <Input
              value={formData.firstName || ""}
              onChange={(e) => handleInputChange("firstName", e.target.value)}
              placeholder="First Name"
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 2 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3 ">
          <FormField label="Last Name *">
            <Input
              value={formData.lastName || ""}
              onChange={(e) => handleInputChange("lastName", e.target.value)}
              placeholder="Last Name"
              disabled={isDisabled}
            />
            {errors.lastName && (
              <span className="text-red-500 text-sm">{errors.lastName}</span>
            )}
          </FormField>
          <FormField label="Mobile">
            <Input
              type="text"
              value={formData.mobile || ""}
              onChange={(e) => handleInputChange("mobile", e.target.value)}
              placeholder="Mobile"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Are You LLQP Licensed">
            <Input
              value={formData.areYouLLQPLicensed || ""}
              onChange={(e) =>
                handleInputChange("areYouLLQPLicensed", e.target.value)
              }
              placeholder="LLQP License"
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 3 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3 ">
          <FormField label="Email">
            <Input
              type="email"
              value={formData.email || ""}
              onChange={(e) => handleInputChange("email", e.target.value)}
              placeholder="Email"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Lead Status Stage">
            <SelectColorCode
              value={formData.leadStatusStage || ""}
              onValueChange={(value) =>
                handleInputChange("leadStatusStage", value)
              }
              options={leadStatusOption.map((name) => ({
                ROWID: name,
                name,
                color: getStatusColor(name) || "#bdbdbd",
              }))}
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Date of Birth">
            <Input
              type="date"
              value={formData.dateOfBirth || ""}
              onChange={(e) => handleInputChange("dateOfBirth", e.target.value)}
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 4 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Assigned Advisor">
            <Select
              value={formData.assignedAdvisor || ""}
              onValueChange={(value) =>
                handleInputChange("assignedAdvisor", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Advisor" />
              </SelectTrigger>
              <SelectContent>
                {adviosers?.map((advisor) => (
                  <SelectItem key={advisor.ROWID} value={advisor.ROWID}>
                    {advisor.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Gender">
            <Select
              value={formData.gender || ""}
              onValueChange={(value) => handleInputChange("gender", value)}
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Gender" />
              </SelectTrigger>
              <SelectContent>
                {genderOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Is This a Reassignment">
            <Select
              value={formData.isThisaReassignment || ""}
              onValueChange={(value) =>
                handleInputChange("isThisaReassignment", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Owner" />
              </SelectTrigger>
              <SelectContent>
                {adviosers?.map((advisor) => (
                  <SelectItem key={advisor.ROWID} value={advisor.ROWID}>
                    {advisor.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 5 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Location Name">
            <Select
              value={formData.locationName || ""}
              onValueChange={(value) =>
                handleInputChange("locationName", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Owner" />
              </SelectTrigger>
              <SelectContent>
                {location?.map((loc) => (
                  <SelectItem key={loc.ROWID} value={loc.ROWID}>
                    {loc.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="If referred by Advisor or External Referral - Name">
            <Select
              value={formData.ifReferredByAdvisorOrExternalReferral || ""}
              onValueChange={(value) =>
                handleInputChange(
                  "ifReferredByAdvisorOrExternalReferral",
                  value
                )
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {objectType.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Net Worth">
            <Select
              value={formData.netWorth || ""}
              onValueChange={(value) => handleInputChange("netWorth", value)}
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Net Worth" />
              </SelectTrigger>
              <SelectContent>
                {understandingOfInsuranceOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 6 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Exchange Rate">
            <Input
              value={formData.exchangeRate || ""}
              onChange={(e) =>
                handleInputChange("exchangeRate", e.target.value)
              }
              placeholder="Exchange Rate"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Preferred Contact Method">
            <Select
              value={formData.preferredContactMethod || ""}
              onValueChange={(value) =>
                handleInputChange("preferredContactMethod", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Method" />
              </SelectTrigger>
              <SelectContent>
                {preferredContactMethodOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Currency">
            <Select
              value={formData.currency || ""}
              onValueChange={(value) => handleInputChange("currency", value)}
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Currency" />
              </SelectTrigger>
              <SelectContent>
                {currency.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 7 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Preferred Contact Time">
            <Select
              value={formData.preferredContactTime || ""}
              onValueChange={(value) =>
                handleInputChange("preferredContactTime", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Time" />
              </SelectTrigger>
              <SelectContent>
                {preferredContactTimeOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Social Media Information?">
            <Select
              value={formData.socialMediaInformation || ""}
              onValueChange={(value) =>
                handleInputChange("socialMediaInformation", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {additionalContactInformationOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Round Robin Assignment Time">
            <Input
              type="datetime-local"
              value={formData.roundRobinAssignmentTime || ""}
              onChange={(e) =>
                handleInputChange("roundRobinAssignmentTime", e.target.value)
              }
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 8 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Citizenship Status">
            <Select
              value={formData.citizenshipStatus || ""}
              onValueChange={(value) =>
                handleInputChange("citizenshipStatus", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Status" />
              </SelectTrigger>
              <SelectContent>
                {citizenshipStatusOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Understanding of Insurance">
            <Select
              value={formData.understandingOfInsurance || ""}
              onValueChange={(value) =>
                handleInputChange("understandingOfInsurance", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Understanding" />
              </SelectTrigger>
              <SelectContent>
                {understandingOfInsuranceOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Existing Insurance Policy?">
            <Select
              value={formData.existingInsurancePolicy || ""}
              onValueChange={(value) =>
                handleInputChange("existingInsurancePolicy", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {objectType.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 9 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Lead Created On">
            <Input
              type="date"
              value={formData.leadCreatedOn || ""}
              onChange={(e) =>
                handleInputChange("leadCreatedOn", e.target.value)
              }
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Existing Policy Renewal Due By">
            <Input
              type="date"
              value={formData.existingPolicyRenewalDueBy || ""}
              onChange={(e) =>
                handleInputChange("existingPolicyRenewalDueBy", e.target.value)
              }
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Old Database Lead?">
            <Select
              value={formData.oldDatabaseLead || ""}
              onValueChange={(value) =>
                handleInputChange("oldDatabaseLead", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {objectType.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 10 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Do you own a home in Canada?">
            <Select
              value={formData.doYouOwnaHomeInCanada || ""}
              onValueChange={(value) =>
                handleInputChange("doYouOwnaHomeInCanada", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {objectType.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Gender Prediction Score">
            <Input
              value={formData.genderPredictionScore || ""}
              onChange={(e) =>
                handleInputChange("genderPredictionScore", e.target.value)
              }
              placeholder="Score"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Do you have life insurance?">
            <Select
              value={formData.doYouhaveLifeInsurance || ""}
              onValueChange={(value) =>
                handleInputChange("doYouhaveLifeInsurance", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {objectType.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 11 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Coverage you are Looking for?">
            <Input
              value={formData.coverageYouAreLookingFor || ""}
              onChange={(e) =>
                handleInputChange("coverageYouAreLookingFor", e.target.value)
              }
              placeholder="Coverage"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Next Follow Up Date & Time">
            <Input
              type="datetime-local"
              value={formData.nextFollowUpDateTime || ""}
              onChange={(e) =>
                handleInputChange("nextFollowUpDateTime", e.target.value)
              }
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Ready to purchase this life insurance policy?">
            <Checkbox
              checked={formData.readyForPurchase || false}
              onCheckedChange={(checked) =>
                handleInputChange("readyForPurchase", checked)
              }
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 12 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Additional Contact Information?">
            <Select
              value={formData.additionalContactInformation || ""}
              onValueChange={(value) =>
                handleInputChange("additionalContactInformation", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {additionalContactInformationOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Submit Page URL">
            <Input
              value={formData.submitPageURL || ""}
              onChange={(e) =>
                handleInputChange("submitPageURL", e.target.value)
              }
              placeholder="URL"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Assigned Campaigns">
            <Input
              value={formData.assignedCampaigns || ""}
              onChange={(e) =>
                handleInputChange("assignedCampaigns", e.target.value)
              }
              placeholder="Campaigns"
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 13 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Gender Prediction">
            <Select
              value={formData.genderPrediction || ""}
              onValueChange={(value) =>
                handleInputChange("genderPrediction", value)
              }
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Gender" />
              </SelectTrigger>
              <SelectContent>
                {genderOption.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Inbox URL">
            <Input
              value={formData.inboxURL || ""}
              onChange={(e) => handleInputChange("inboxURL", e.target.value)}
              placeholder="URL"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Phone">
            <Input
              type="number"
              value={formData.phoneNumber || ""}
              onChange={(e) => handleInputChange("phoneNumber", e.target.value)}
              placeholder="Phone"
              disabled={isDisabled}
            />
          </FormField>
        </div>

        {/* Row 14 */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-3">
          <FormField label="Secondary Email">
            <Input
              type="email"
              value={formData.secondaryEmail || ""}
              onChange={(e) =>
                handleInputChange("secondaryEmail", e.target.value)
              }
              placeholder="Email"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Fax">
            <Input
              type="number"
              value={formData.fax || ""}
              onChange={(e) => handleInputChange("fax", e.target.value)}
              placeholder="Fax"
              disabled={isDisabled}
            />
          </FormField>
          <FormField label="Referred by">
            <Select
              value={formData.referredBy || ""}
              onValueChange={(value) => handleInputChange("referredBy", value)}
              disabled={isDisabled}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select" />
              </SelectTrigger>
              <SelectContent>
                {referredByOptions.map((option) => (
                  <SelectItem key={option} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>

        {/* Row 15 - Checkboxes */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-5">
          <div className="flex gap-5 items-center">
            <Checkbox
              checked={formData.roundRobinProcessed || false}
              onCheckedChange={(checked) =>
                handleInputChange("roundRobinProcessed", checked)
              }
              disabled={isDisabled}
            />
            <FormField label="Round Robin Processed"></FormField>
          </div>
          <div className="flex gap-5 items-center">
              <Checkbox
                checked={formData.emailRoundRobinOwner || false}
                onCheckedChange={(checked) =>
                  handleInputChange("emailRoundRobinOwner", checked)
                }
                disabled={isDisabled}
              />
            <FormField label="Email Round Robin Owner">
            </FormField>
          </div>
          <div className="flex gap-5 items-center">
              <Checkbox
                checked={formData.eligibleRoundRobinOwnerFound || false}
                onCheckedChange={(checked) =>
                  handleInputChange("eligibleRoundRobinOwnerFound", checked)
                }
                disabled={isDisabled}
              />
            <FormField label="Eligible Round Robin Owner Found">
            </FormField>
          </div>
        </div>

        {/* Row 16 - Checkboxes */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-5">
          <div className="flex gap-5 items-center">
            <Checkbox
              checked={formData.reRunRoundRobin || false}
              onCheckedChange={(checked) =>
                handleInputChange("reRunRoundRobin", checked)
              }
              disabled={isDisabled}
            />
            <FormField label="Re-Run Round Robin"></FormField>
          </div>
          <div className="flex gap-5 items-center">
            <Checkbox
              checked={formData.rcSmsOptOut || false}
              onCheckedChange={(checked) =>
                handleInputChange("rcSmsOptOut", checked)
              }
              disabled={isDisabled}
            />
            <FormField label="RC SMS Opt Out"></FormField>
          </div>
        </div>

        {/* Full width row for Description */}
        <div className="grid grid-cols-1 gap-4 my-3">
          <FormField label="Description">
            <Textarea
              value={formData.description || ""}
              onChange={(e) => handleInputChange("description", e.target.value)}
              placeholder="Description"
              rows={4}
              disabled={isDisabled}
            />
          </FormField>
        </div>
      </FormCard>

      {/* <div
        className="button-row d-flex justify-content-center mt-4 gap-4"
        style={{ marginBottom: "200px" }}
      >
        <button
          className="btn mb-0 bg-gradient-dark btn-md null null js-btn-next"
          onClick={handleNext}
          type="button"
          disabled={isDisabled}
        >
          Next
        </button>
      </div> */}
    </div>
  );
};

export default LeadInformation;

// client/app/src/views/leads/leadAdvisorForm/leadAdvisorFormComponents/LeadInformation.vue
<template>
  <div class="card">
    <!-- Personal Details -->
    <div class="card custom-card">
      <div class="card-header pb-0">
        <h5 class="main-heading  mb-2 ps-1">Personal Details</h5>
        <div class="card-body">
          <div class="card-surface mb-2">
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="assignedAdvisor">Insurance Lead Owner <span
                    class="text-danger">*</span></label>
                <SingleSlelect class="form-select " id="insuranceLeadOwner" v-model="formData.insuranceLeadOwner"
                  :options="owners" />
                <span v-if="errors.insuranceLeadOwner" class="text-danger">{{
                  errors.insuranceLeadOwner
                  }}</span>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="insuranceLeadSource">Insurance Lead Source</label>
                <select class="form-select" id="insuranceLeadSource" v-model="formData.insuranceLeadSource">
                  <option v-for="(option, index) in insuranceLeadSourceOptions" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="firstName">First Name</label>
                <input type="text" id="firstName" v-model="formData.firstName" class="form-control" />
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="lastName">Last Name</label>
                <input type="text" id="lastName" v-model="formData.lastName" class="form-control" />
                <span v-if="errors.lastName" class="text-danger">{{
                  errors.lastName
                  }}</span>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="mobile">Mobile</label>
                <input type="text" id="mobile" v-model="formData.mobile" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="areYouLLQPLicensed">Are You LLQP Licensed</label>
                <input type="text" id="areYouLLQPLicensed" v-model="formData.areYouLLQPLicensed" class="form-control" />
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="email">Email</label>
                <input type="email" id="email" v-model="formData.email" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="leadStatusStage">Lead Status Stage</label>
                <!-- <select class="form-select" id="leadStatusStage" v-model="formData.leadStatusStage">
      
          <option v-for="(option, index) in leadStatusOption" :key="index" :value="option">
            {{ option }}
          </option>
        </select> -->
                <SelectColorCode v-model="formData.leadStatusStage" :options="leadStatusOption" />

              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="dateOfBirth">Date of Birth</label>
                <input type="date" id="dateOfBirth" v-model="formData.dateOfBirth" class="form-control" />
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="assignedAdvisor">Assigned Advisor</label>
                <select class="form-select" id="assignedAdvisorOwner" v-model="formData.assignedAdvisor">
                  <option value="" disabled selected class="text-muted">
                    Select Owner
                  </option>
                  <option v-for="(userData, index) in adviosers" :key="index" :value="userData.ROWID">
                    {{ userData.name }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="gender">Gender</label>
                <select id="gender" v-model="formData.gender" class="form-select">
                  <option v-for="(option, index) in genderOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="isThisaReassignment">Is This a Reassignment</label>
                <select class="form-select" id="assignedAdvisorOwner" v-model="formData.isThisaReassignment">
                  <option value="" disabled selected class="text-muted">
                    Select Owner
                  </option>
                  <option v-for="(userData, index) in adviosers" :key="index" :value="userData.ROWID">
                    {{ userData.name }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="locationName">Location Name</label>
                <select class="form-select" id="locationNameOwner" v-model="formData.locationName">
                  <option value="" disabled selected class="text-muted">
                    Select Owner
                  </option>
                  <option v-for="(userData, index) in location" :key="index" :value="userData.ROWID">
                    {{ userData.name }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="genderPrediction">If referred by Advisor or External Referral -
                  Name</label>
                <select class="form-select" id="genderPrediction"
                  v-model="formData.ifReferredByAdvisorOrExternalReferral">
                  <option v-for="(option, index) in objectType" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="netWorth">Net Worth</label>
                <select class="form-select" id="netWorth" v-model="formData.netWorth">
                  <option v-for="(option, index) in understandingOfInsuranceOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="exchangeRate">Exchange Rate</label>
                <input type="text" id="exchangeRate" v-model="formData.exchangeRate" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="preferredContactMethod">Preferred Contact Method</label>
                <select id="gender" v-model="formData.preferredContactMethod" class="form-select">
                  <option v-for="(option, index) in preferredContactMethodOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="currency">Currency</label>
                <select v-model="formData.currency" class="form-select">
                  <option v-for="(option, index) in currency" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
            </div>


          </div>
        </div>
        <div class="card-body">
          <div class="card-surface mb-2">
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="preferredContactTime">Preferred Contact Time</label>
                <select id="gender" v-model="formData.preferredContactTime" class="form-select">
                  <option v-for="(option, index) in preferredContactTimeOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="socialMediaInformation">Social Media Information?</label>
                <select id="socialMediaInformation" v-model="formData.socialMediaInformation" class="form-select">
                  <option v-for="(option, index) in additionalContactInformationOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="roundRobinAssignmentTime">Round Robin Assignment Time</label>
                <input type="datetime-local" id="roundRobinAssignmentTime" v-model="formData.roundRobinAssignmentTime"
                  class="form-control" />
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="citizenshipStatus">Citizenship Status</label>
                <select class="form-select" id="citizenshipStatus" v-model="formData.citizenshipStatus">
                  <option v-for="(option, index) in citizenshipStatusOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="understandingOfInsurance">Understanding of Insurance</label>
                <select class="form-select" id="understandingOfInsurance" v-model="formData.understandingOfInsurance">
                  <option v-for="(option, index) in understandingOfInsuranceOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2">Existing Insurance Policy?</label>
                <select class="form-select" v-model="formData.existingInsurancePolicy">
                  <option v-for="(option, index) in objectType" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="leadCreatedOn">Lead Created On</label>
                <input type="date" id="leadCreatedOn" v-model="formData.leadCreatedOn" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="existingInsurancePolicy">Existing Policy Renewal Due By</label>
                <input type="date" id="existingInsurancePolicy" v-model="formData.existingPolicyRenewalDueBy"
                  class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2">Old Database Lead?</label>
                <select class="form-select" v-model="formData.oldDatabaseLead">
                  <option v-for="(option, index) in objectType" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2">Do you own a home in Canada? </label>
                <select class="form-select" v-model="formData.doYouOwnaHomeInCanada">
                  <option v-for="(option, index) in objectType" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="genderPredictionScore">Gender Prediction Score</label>
                <input type="text" class="form-control" id="genderPredictionScore"
                  v-model="formData.genderPredictionScore" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2">Do you have life insurance? </label>
                <select class="form-select" v-model="formData.doYouhaveLifeInsurance">
                  <option v-for="(option, index) in objectType" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="coverageYouAreLookingFor">Coverage you are Looking for?</label>
                <input type="text" id="coverageYouAreLookingFor" v-model="formData.coverageYouAreLookingFor"
                  class="form-control" />
              </div>
              <!-- <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="mb-0 mt-2" for="areYouReadyToPurchaseThisLifeInsurancePoli">Are you ready to purchase this Life
          Insurance Policy</label>
        <input type="text" id="areYouReadyToPurchaseThisLifeInsurancePoli"
          v-model="formData.areYouReadyToPurchaseThisLifeInsurancePoli" class="form-control" />
      </div> -->
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="nextFollowUpDateTime">Next Follow Up Date & Time</label>
                <input type="datetime-local" id="nextFollowUpDateTime" v-model="formData.nextFollowUpDateTime"
                  class="form-control" />
              </div>
              <!-- <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
        <div class="d-flex justify-content-start align-items-center">
          <label class="my-0 mx-2">Are you ready to purchase this Life Insurance Policy</label>
          <input v-model="formData.areYouReadyToPurchaseThisLifeInsurancePol" type="checkbox"
            class="form-check-input border" />
        </div>
      </div> -->
              <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
                <div class="d-flex justify-content-start align-items-center">
                  <label class="mt-4 mx-2">Ready to purchase this life insurance policy?</label>
                  <input v-model="formData.readyForPurchase" type="checkbox" class="form-check-input border mt-4"
                    style="width: 16px; height: 16px;" />
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2">Additional Contact Information? </label>
                <select class="form-select" v-model="formData.additionalContactInformation">
                  <option v-for="(option, index) in additionalContactInformationOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="submitPageURL">Submit Page URL</label>
                <input type="text" id="submitPageURL" v-model="formData.submitPageURL" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="assignedCampaigns">Assigned Campaigns</label>
                <input type="text" id="assignedCampaigns" v-model="formData.assignedCampaigns" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="genderPrediction">Gender Prediction</label>
                <select class="form-select" id="genderPrediction" v-model="formData.genderPrediction">
                  <option v-for="(option, index) in genderOption" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="inboxURL">Inbox URL</label>
                <input type="text" id="inboxURL" v-model="formData.inboxURL" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="phoneNumber">Phone</label>
                <input type="number" id="phoneNumber" v-model="formData.phoneNumber" class="form-control" />
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="secondaryEmail">Secondary Email</label>
                <input type="text" id="secondaryEmail" v-model="formData.secondaryEmail" class="form-control" />
              </div>

              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="secondaryEmail">Fax</label>
                <input type="number" id="secondaryEmail" v-model="formData.fax" class="form-control" />
              </div>

              <div class="col-lg-4 col-md-4 col-sm-12">
                <label class="mb-0 mt-2" for="Referred-by">Referred by</label>
                <select class="form-select" id="Referred-by" v-model="formData.referredBy">
                  <option v-for="(option, index) in referredByOptions" :key="index" :value="option">
                    {{ option }}
                  </option>
                </select>
              </div>
            </div>
            <div class="row m-2 py-2 ps-2">
              <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
                <div class="d-flex justify-content-start align-items-center">
                  <label class="my-0 mx-2">Round Robin Processed</label>
                  <input v-model="formData.roundRobinProcessed" type="checkbox" class="form-check-input border"
                    style="width: 16px; height: 16px;" />
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
                <div class="d-flex justify-content-start align-items-center">
                  <label class="my-0 mx-2">Email Round Robin Owner</label>
                  <input v-model="formData.emailRoundRobinOwner" type="checkbox" class="form-check-input border"
                    style="width: 16px; height: 16px;" />
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
                <div class="d-flex justify-content-start align-items-center">
                  <label class="my-0 mx-2">Eligible Round Robin Owner Found</label>
                  <input v-model="formData.eligibleRoundRobinOwnerFound" type="checkbox" class="form-check-input border"
                    style="width: 16px; height: 16px;" />
                </div>
              </div>
              <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
                <div class="d-flex justify-content-start align-items-center">
                  <label class="my-0 mx-2">Re-Run Round Robin</label>
                  <input v-model="formData.reRunRoundRobin" type="checkbox" class="form-check-input border"
                    style="width: 16px; height: 16px;" />
                </div>
              </div>

              <div class="col-lg-4 col-md-4 col-sm-12 mt-3">
                <div class="d-flex justify-content-start align-items-center">
                  <label class="my-0 mx-2">RC SMS Opt Out</label>
                  <input v-model="formData.rcSmsOptOut" type="checkbox" class="form-check-input border"
                    style="width: 16px; height: 16px;" />
                </div>
              </div>
            </div>
            <div class="row ps-2">
              <div class="col-lg-12 col-md-12 col-sm-12">
                <label class="mb-0 mt-2" for="additionalNotes">Description</label>
                <textarea id="additionalNotes" rows="4" v-model="formData.description" class="form-control"></textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



  </div>
  <div class="button-row d-flex justify-content-center mt-4 gap-4" style="margin-bottom:200px;">
    <button class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" @click.prevent="nextStep" type="button">
      Next
    </button>
  </div>
</template>

<script>
import mandatory from "../../utils/mandatroy.js";
import validateMandatoryFields from "../../../utils/util-js/validate.js";
import { getStatusColor } from "../../../utils/util-js/statusColorMap.js"; // ✅ Make sure this file exists

import {
  insuranceLeadSourceOptions,
  leadStatusOption,
  genderOption,
  objectType,
  additionalContactInformationOption,
  understandingOfInsuranceOption,
  citizenshipStatusOption,
  preferredContactTimeOption,
  preferredContactMethodOption,
  referredByOptions,
  currency
} from "../../utils/picklist";
import axios from "axios";
import { putUrl } from "../../../../boot/axios";
import { ref } from "vue";

import SingleSlelect from "../../../utils/SingleSlelect.vue";
import SelectColorCode from "../../../utils/SelectColorCode.vue";

export default {
  name: "ApplicationForm",
  props: {
    LeadInformation: {
      type: Object,
      required: true,
    },
    owners: {
      type: Array,
      required: true,
    },
    adviosers: {
      type: Array,
      required: true,
    },
    location: {
      type: Array,
      required: true,
    },
  },
  components: {
    SingleSlelect,
    SelectColorCode
  },
  data() {
    return {
      formData: { ...this.LeadInformation },
      insuranceLeadSourceOptions: { ...insuranceLeadSourceOptions },
      leadStatusOption: [],
      genderOption: { ...genderOption },
      objectType: { ...objectType },
      additionalContactInformationOption: {
        ...additionalContactInformationOption,
      },
      understandingOfInsuranceOption: { ...understandingOfInsuranceOption },
      citizenshipStatusOption: { ...citizenshipStatusOption },
      preferredContactTimeOption: { ...preferredContactTimeOption },
      referredByOptions: { ...referredByOptions },
      preferredContactMethodOption: { ...preferredContactMethodOption },
      errors: {},
      assignedOwner: ref([]),
      locationNameOwner: ref([]),
      assignedAdvisorOwner: ref([]),
      currency: [...currency]
    };
  },


  created() {
    this.leadStatusOption = leadStatusOption.map(name => ({
      ROWID: name,
      name,
      color: getStatusColor(name) || "#bdbdbd" // fallback if undefined
    }));
  },


  watch: {
    LeadInformation: {
      handler(formData) {
        formData = { ...this.LeadInformation };
        console.log("FormData lead LeadInformation: ", formData);
      },
      immediate: true,
      deep: true,
    },
  },
  methods: {
    async getallusers() {
      try {
        const response = await axios.get(
          `${putUrl}uatServerFunction/api/v1/getAllUsers`
        );
        this.assignedOwner = response.data.map((item) => item.userData);

        console.log("this.assignedOwner <====>", this.assignedOwner);
      } catch (error) {
        console.error("Error fetching users:", error);
      }
    },
    async getAdvisors() {
      try {
        const response = await axios.get(
          `${putUrl}uatServerFunction/api/v1/getAllAdvisor`
        );
        this.assignedAdvisorOwner = response.data.map((item) => item.advisors);
      } catch (error) {
        console.error("Error fetching users:", error);
      }
    },
    async getLocations() {
      try {
        const response = await axios.get(
          `${putUrl}uatServerFunction/api/v1/getAllLocations`
        );
        this.locationNameOwner = response.data.map((item) => item.locations);
      } catch (error) {
        console.error("Error fetching users:", error);
      }
    },
    nextStep() {
      this.errors = validateMandatoryFields(this.formData, mandatory);
      const validateFields = Object.keys(this.errors).length === 0;
      if (validateFields) {
        this.$emit("next", this.formData);
      }
    },
    // nextStep() {
    //   this.$emit('next', this.formData);
    // },
  },
};
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.multisteps-form__content label {
  font-size: var(--crm-font-regular) !important;
  margin-top: 1rem;
  margin-bottom: 0.5rem;
  margin-bottom: 0.5rem;
  font-weight: 500 !important;
  /* font-style: ; */
  /* font-family: */
}

.multisteps-form .main-heading {
  font-weight: 500 !important;
}

select {
  height: 2.5rem !important;
  padding: 0px 0px 0px 10px !important;
}

.multisteps-form__panel {
  position: relative !important;
  display: none !important;
  transition: padding 0.3s ease;
  /* Add transition for smoother padding change */
  padding-bottom: 0;
  /* Initially set padding bottom to 0 */
}

.multisteps-form__panel.js-active {
  display: block !important;
}

.select-box select {
  display: content !important;
  border: 1px solid #e0e3e7 !important;
  border-radius: 10px;
}

.error {
  color: red;
  position: absolute;
}

.input-error-font-size {
  font-size: 12px;
}

.highlight {
  border: 1px solid red !important;
}
</style>
