// frontend/src/features/crm/pages/advisor/leadAdvisorFormComponents/ReferralInformation.jsx
import React, { useState, useEffect } from 'react';
import { FormCard, FormField } from '@/components/custom/CustomFormComponents';
import { Input } from '@/components/ui/input';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { referralSourceOption, yearOption, productCategoryOption } from '../utils/picklist';

const ReferralInformation = ({ ReferralInformation, contacts, referral, leadSource, onNext, onPrevious }) => {
  const [formData, setFormData] = useState({ ...ReferralInformation });
  const [contactsArr, setContactsArr] = useState([...contacts]);
  const [referralArr, setReferralArr] = useState([...referral]);

  useEffect(() => {
    setFormData({ ...ReferralInformation });
  }, [ReferralInformation]);

  useEffect(() => {
    setContactsArr([...contacts]);
  }, [contacts]);

  useEffect(() => {
    setReferralArr([...referral]);
  }, [referral]);

  const handleInputChange = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleNext = () => {
    onNext(formData);
  };

  const handlePrevious = () => {
    onPrevious();
  };

  if (leadSource?.toLowerCase() !== 'referral') {
    return (
      <div className="d-flex justify-content-center align-items-center" style={{ minHeight: '200px' }}>
        <span className="text-muted">Please select lead in lead Info as Referral to enter referral information.</span>
      </div>
    );
  }

  return (
    <div>
      <FormCard title="Referral Information">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <FormField label="Referred By">
            <Select
              value={formData.referredBy || ''}
              onValueChange={(value) => handleInputChange('referredBy', value)}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Referred By" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="-None-">-None-</SelectItem>
                <SelectItem value="Social Media">Social Media</SelectItem>
                <SelectItem value="Radio">Radio</SelectItem>
                <SelectItem value="Google">Google</SelectItem>
                <SelectItem value="Advisor">Advisor</SelectItem>
                <SelectItem value="External Referral">External Referral</SelectItem>
                <SelectItem value="Lead/Client">Lead/Client</SelectItem>
                <SelectItem value="Mortgage/RealEstate/Accountant">Mortgage/RealEstate/Accountant</SelectItem>
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Year">
            <Select
              value={formData.year || ''}
              onValueChange={(value) => handleInputChange('year', value)}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Year" />
              </SelectTrigger>
              <SelectContent>
                {yearOption.map((option, index) => (
                  <SelectItem key={index} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Referral Source">
            <Select
              value={formData.referralSource || ''}
              onValueChange={(value) => handleInputChange('referralSource', value)}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Referral Source" />
              </SelectTrigger>
              <SelectContent>
                {referralSourceOption.map((option, index) => (
                  <SelectItem key={index} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Referral Client">
            <Select
              value={formData.referralClient || ''}
              onValueChange={(value) => handleInputChange('referralClient', value)}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Referral Client" />
              </SelectTrigger>
              <SelectContent>
                {contactsArr.map(contact => (
                  <SelectItem key={contact.ROWID} value={contact.ROWID}>
                    {contact.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Referral Other than Client">
            <Select
              value={formData.referralOtherThanClient || ''}
              onValueChange={(value) => handleInputChange('referralOtherThanClient', value)}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Referral" />
              </SelectTrigger>
              <SelectContent>
                {referralArr.map(ref => (
                  <SelectItem key={ref.ROWID} value={ref.ROWID}>
                    {ref.referralName}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
          <FormField label="Product Category Referred">
            <Select
              value={formData.productCategoryReferred || ''}
              onValueChange={(value) => handleInputChange('productCategoryReferred', value)}
            >
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select Product Category" />
              </SelectTrigger>
              <SelectContent>
                {productCategoryOption.map((option, index) => (
                  <SelectItem key={index} value={option}>
                    {option}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </FormField>
        </div>
      </FormCard>
    </div>
  );
};

export default ReferralInformation;

// client/app/src/views/leads/leadAdvisorForm/leadAdvisorFormComponents/ReferralInformation.vue
<template>
  <div v-if="leadSource?.toLowerCase() === 'referral'">
    <h5 class="main-heading mt-2 mb-0 ps-2">Referral Information</h5>

    <div class="row ps-2">
       <div  class="col-lg-4 col-md-4 col-sm-12">
        <label class="mb-0 mt-2" for="year">Referred By</label>
         <select class="form-select" v-model="formData.referredBy">
          <option value="-None-">-None-</option>
          <option value="Social Media">Social Media</option>
          <option value="Radio">Radio</option>
          <option value="Google">Google</option>
          <option value="Advisor">Advisor</option>
          <option value="External Referral">External Referral</option>
          <option value="Lead/Client">Lead/Client</option>
          <option value="Mortgage/RealEstate/Accountant">Mortgage/RealEstate/Accountant</option>
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="mb-0 mt-2" for="year">Year</label>
        <select class="form-select" v-model="formData.year">
          <option v-for="(option, index) in yearOption" :key="index" :value="option">
            {{ option }}
          </option>

        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Referral Source</label>
        <select class="form-select" v-model="formData.referralSource">
          <option v-for="(option, index) in referralSourceOption" :key="index" :value="option">
            {{ option }}
          </option>

        </select>
      </div>
     

    

    </div>
    <div class="row mt-1 ps-2">
        <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Referral Client</label>
        <select class="form-select" v-model="formData.referralClient">
          <option v-for="contact in contactsArr" :key="contact.ROWID" :value="contact.ROWID">
            {{ contact.name }}
          </option>
          <!-- <option value="Manreet Singh Walia">Manreet Singh Walia</option>
          <option value="Samilla Christine Barbosa Ribeiro Mendes">Samilla Christine Barbosa Ribeiro Mendes</option> -->
          <!-- Remove duplicate option if not needed -->
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Referral Other than Client</label>
        <select class="form-select" v-model="formData.referralOtherThanClient">
          <option v-for="referral in referralArr" :key="referral.ROWID" :value="referral.ROWID">
            {{ referral.referralName }}
          </option>
          <!-- <option value="">-None-</option>
          <option value="Harjit Singh Warring">Harjit Singh Warring</option> -->
        </select>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-12">
        <label class="my-0">Product Category Referred</label>
        <select class="form-select" v-model="formData.productCategoryReferred">
          <option v-for="(option, index) in productCategoryOption" :key="index" :value="option">
            {{ option }}
          </option>

        </select>
      </div>
    </div>

    <div class="button-row d-flex justify-content-center mt-4 gap-4" style="margin-bottom:200px;">
      <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" @click="previousStep"
        type="button">Prev</button>
      <button class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" @click.prevent="nextStep"
        type="button">Next</button>
    </div>
  </div>
  <div v-else class="d-flex justify-content-center align-items-center" style="min-height: 200px;">
    <span class="text-muted">Please select lead in lead Info as Referral to enter referral information.</span>
  </div>
</template>

<script>
import { referralSourceOption, siblingsOption, dependentParentsOption, yearOption, productCategoryOption } from "../../utils/picklist.js";

export default {
  name: "CampaignDataForm",
  props: {
    ReferralInformation: {
      type: Object,
      required: true
    },
    contacts: {
      type: Array,
      required: true,
    },
    referral: {
      type: Array,
      required: true,
    },
    leadSource: {
      type: String,
      default: ''
    }

  },
  data() {
    return {
      formData: { ...this.ReferralInformation },
      contactsArr: [...this.contacts],
      referralArr: [...this.referral],
      yearOption: { ...yearOption },
      referralSourceOption: { ...referralSourceOption },
      productCategoryOption: { ...productCategoryOption },
      siblingsOption: { ...siblingsOption },
      dependentParentsOption: { ...dependentParentsOption },
    };
  },
  watch: {
    ReferralInformation: {
      handler() {
        this.formData = { ...this.ReferralInformation };
        console.log("FormData lead ReferralInformation: ", this.formData);
      },
      immediate: true,
      deep: true
    },
    contacts: {
      handler(contactsArr) {
        contactsArr = this.contacts;
        console.log("this contactsArr", contactsArr);
      },
      immediate: true,
      deep: true,
    },
    referral: {
      handler(referralArr) {
        referralArr = this.referral;
        console.log("this contactsArr", referralArr);
      },
      immediate: true,
      deep: true,
    },
    leadSource: {
      handler(newVal) {
        console.log('Lead Source changed:', newVal);
      },
      immediate: true
    },
  },

  created() {
    console.log('Initial Lead Source:', this.leadSource);
  },
  methods: {
    nextStep() {
      this.$emit('next', this.formData);
    },
    previousStep() {
      this.$emit('previous');
    },
  }
};
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
</style>
