// client/app/src/views/Policies/Policy/Components/claims.vue
<template>
    <div>
      <h5 class="main-heading mt-2 ps-2">Claim</h5>
      <div class="col-lg-4 col-sm-6 mt-2 mt-sm-0 ps-2">
                  <label class="my-0">Any Current Claims on this Policy?</label>
                  <div
                    class="choices"
                    data-type="select-one"
                    tabindex="0"
                    role="listbox"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    <div class="select-box mb-3">
                      <select
                        v-model="formData.areCurrentClaimonThisPolicy"
                        id="choices-state"
                        class="multisteps-form__select form-control choices__input"
                        name="choices-state"
                        tabindex="-1"
                        data-choice="active"
                      >
                      <option  v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option" :checked="option === '-None-'">{{ option }}</option>

                      </select>
                    </div>
                    
                  </div>
      </div>
      <div class="col-lg-4 col-sm-6 mt-2 mt-sm-0 ps-2">
                  <label class="my-0">Any Past Claims on this Policy?</label>
                  <div
                    class="choices"
                    data-type="select-one"
                    tabindex="0"
                    role="listbox"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    <div class="select-box mb-3">
                      <select
                        v-model="formData.arePastClaimonThisPolicy"
                        id="choices-state"
                        class="multisteps-form__select form-control choices__input"
                        name="choices-state"
                        tabindex="-1"
                        data-choice="active"
                      >
                      <option  v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option" :checked="option === '-None-'">{{ option }}</option>

                      </select>
                    </div>
                    
                  </div>
      </div>
      <div class="col-lg-4 col-sm-6 mt-2 mt-sm-0 ps-2">
                  <label class="my-0">Claim Outcome</label>
                  <div
                    class="choices"
                    data-type="select-one"
                    tabindex="0"
                    role="listbox"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    <div class="select-box mb-3">
                      <select
                        v-model="formData.claimOutcome"
                        id="choices-state"
                        class="multisteps-form__select form-control choices__input"
                        name="choices-state"
                        tabindex="-1"
                        data-choice="active"
                      >
                      <option  v-for="(option, index) in claimOutcomeOption" :key="index" :value="option" :checked="option === '-None-'">{{ option }}</option>

                       
                      </select>
                    </div>
                    
                  </div>
      </div>
      <div style="width: 100%; overflow: scroll">
        <table class="table border table-responsive subform">
          <thead class="table subform-table-head text-white">
            <tr>
              <th>#</th>
              <th>Actions</th>
              <th>Date of claim</th>
              <th>Reason for claim</th>
              <th>Amount of Claim (CA$)</th>
              <th>Claim Closed On</th>
              <th>Claim Amount Settled (CA$)</th>
              <th>Claim Amount Rejected (CA$)</th>
              <th>Settlement Observations if any</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <tr v-for="(parent, index) in pastClaims" :key="index">
              <td class="m-auto">{{ index + 1 }}</td>
              <td>
                <a @click.prevent="deleteClaimRow(index)" href="javascript:;" data-bs-toggle="tooltip" data-bs-original-title="Delete product">
                  <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
                </a>
              </td>
              
              <td>
                <!-- <input v-model="parent.dateOfClaim" type="date" class="form-control form-control-default" autocomplete="off"> -->
                  <div class="input-group bg-white">
            <flat-pickr v-model="parent.dateOfClaim" :config="datePickerConfig" placeholder="DD/MM/YYYY"
              class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
              ref="fpDateOfBirth" />
            <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
              </td>
              <td>
                <textarea v-model="parent.reasonforClaim" class="form-control form-control-default" rows="1"></textarea>
              </td>
             
              <td>
                <input v-model="parent.amountofClaim" type="number" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
              
                <div class="input-group bg-white">
            <flat-pickr v-model="parent.claimClosedOn" :config="datePickerConfig" placeholder="DD/MM/YYYY"
              class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
              ref="fpDateOfBirth" />
            <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
              </td>
              
              <td>
                <input v-model="parent.claimAmountSettled" type="number" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
                <input v-model="parent.claimAmountRejected" type="number" class="form-control form-control-default" autocomplete="off">
              </td>
              <td>
                <textarea v-model="parent.settlement" class="form-control form-control-default" rows="1"></textarea>
              </td>
             

            </tr>
          </tbody>
        </table>
        
      </div>
      <button class="btn mb-0 btn-color btn-md" type="button" @click.prevent="addRowToClaimTable">
        Add Row
      </button>
    </div>
    <h5 class="main-heading mt-2 ps-2">Past Claims</h5>
            <div class="row multisteps-form__content ps-2">
              <div class="col-md-4 col-sm-12 mt-2 ">
                <label class="my-0">Total Amount Claimed</label>
                <div class="col-12">
                  <input
                    v-model="formData.totalAmountClaimed"
                    placeholder="$"
                    type="number"
                    class="form-control form-control-default"
                    isrequired="false"
                    autocomplete="off"
                  />
                </div>
              </div>
              <div class="col-md-4 col-sm-12 mt-2 ">
                <label class="my-0">Total Amount Settled</label>
                <div class="col-12">
                  <input
                    v-model="formData.totalAmountSettled"
                    placeholder="CA$"
                    type="number"
                    class="form-control form-control-default"
                    isrequired="false"
                    autocomplete="off"
                  />
                </div>
              </div>
              <div class="col-md-4 col-sm-12 mt-2 ps-2">
                <label class="my-0">Total Amount Rejected</label>
                <div class="col-12">
                  <input
                    v-model="formData.totalAmountRejected"
                    placeholder="$"
                    type="number"
                    class="form-control form-control-default"
                    isrequired="false"
                    autocomplete="off"
                  />
                </div>
              </div>
            </div>
            <h5 class="main-heading mt-2 ps-2">SMS Response</h5>
            <div class="multisteps-form__content ps-2">
              <div class="col-12 col-sm-12 mt-2">
                <label class="my-0">Ringcentral sms response</label>
                <div class="col-12">
                  <textarea
                    v-model="formData.ringcentralSmsResponse"
                    type="text"
                    class="form-control form-control-default"
                    isrequired="false"
                    autocomplete="off"
                  />
                </div>
              </div>
            </div>
    <div class="button-row d-flex justify-content-center mt-4 gap-4 space">
                <button
                  class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev"
                  type="button"
                  @click.prevent="previousStep"
                >
                  Prev
                </button>
                <button
                  class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next"
                  type="button"
                  @click.prevent="nextStep"
                >
                  Next
                </button>
              </div>
  </template>
  <script>
  import {clientFirstPolicyOptions, claimOutcomeOption } from "../../utils/picklist";

import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
  export default {
     components: { flatPickr },
    name: "LeadManagementHistory",
    props: {
      claims:{
        type: Object,
        required: true
      }
    },
    watch:{
      claims:{
        handler(){
          this.formData = {...this.claims}
          this.pastClaims = this.claims.pastClaims || [];
        },
        immediate: true,
        deep: true,
      }
    },
    data() {
      return {
        datePickerConfig: {
        dateFormat: "d/m/Y", // DD/MM/YYYY
        allowInput: true
      },
      dateTimePickerConfig: {
        dateFormat: "d/m/Y H:i", // DD/MM/YYYY HH:mm
        allowInput: true,
        enableTime: true,
        time_24hr: true
      },
        formData: {...this.claims},
        pastClaims:[],
        clientFirstPolicyOptions:{...clientFirstPolicyOptions},
        claimOutcomeOption:{...claimOutcomeOption}      
      };
    },   
    methods: {      
       openDatePicker() {
      if (this.$refs.fpDateOfBirth && this.$refs.fpDateOfBirth.fp) {
        this.$refs.fpDateOfBirth.fp.open()
      }
    },
      addRowToClaimTable() {
        this.pastClaims.push({
            dateOfClaim:"",
            reasonforClaim:"",
            amountofClaim:"",
            claimClosedOn:"",
            claimAmountSettled:"",
            claimAmountRejected:"",
            settlement:""
        });
      },
      deleteClaimRow(index) {
        this.pastClaims.splice(index, 1);
      },
      nextStep() {
        this.$emit('next', {...this.formData,pastClaims:this.pastClaims});
      },
      previousStep() {
        this.$emit('previous');
    }
  }
}
  </script>
  
  <style scoped>
  .main-heading {
    font-weight: 500 !important;
  }
  
  .form-control-default {
    border: 1px solid #ccc;
    border-radius: 4px;
    padding: 0.5rem;
    width: 100%;
  }
  
  .my-0 {
    margin-bottom: 0 !important;
  }
  @media screen and (max-width:500px) {
  .space{
    margin-bottom:150px;
  }
}
  </style>

// frontend/src/features/Policy/policyFormComponents/Claims.jsx
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { format } from "date-fns";
import { Trash2 } from "lucide-react";

const Claims = ({ formData, setFormData, onNext, onPrev, isDisabled }) => {
  const [pastClaims, setPastClaims] = useState(formData.pastClaims || []);

  const handleChange = (field, value) => {
    setFormData({ ...formData, [field]: value });
  };

  const addRowToClaimTable = () => {
    setPastClaims([
      ...pastClaims,
      {
        dateOfClaim: "",
        reasonforClaim: "",
        amountofClaim: "",
        claimClosedOn: "",
        claimAmountSettled: "",
        claimAmountRejected: "",
        settlement: "",
      },
    ]);
  };

  const deleteClaimRow = (index) => {
    setPastClaims(pastClaims.filter((_, i) => i !== index));
  };

  const handleNext = () => {
    setFormData({ ...formData, pastClaims });
    onNext();
  };

  const clientFirstPolicyOptions = ["-None-", "Yes", "No"];
  const claimOutcomeOption = ["-None-", "Rejected", "Pending"];

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>Claim</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">

            {/* ------- Select 1 ------- */}
            <div>
              <Label className="mb-2">Any Current Claims on this Policy?</Label>
              <Select
                value={formData.areCurrentClaimonThisPolicy}
                onValueChange={(value) => handleChange("areCurrentClaimonThisPolicy", value)}
                disabled={isDisabled}
              >
                <SelectTrigger
                  className={`w-full ${!isDisabled ? "border-2 border-gray-300" : ""}`}
                  disabled={isDisabled}
                >
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {clientFirstPolicyOptions.map((option) => (
                    <SelectItem key={option} value={option} disabled={isDisabled}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* ------- Select 2 ------- */}
            <div>
              <Label className="mb-2">Any Past Claims on this Policy?</Label>
              <Select
                value={formData.arePastClaimonThisPolicy}
                onValueChange={(value) => handleChange("arePastClaimonThisPolicy", value)}
                disabled={isDisabled}
              >
                <SelectTrigger
                  className={`w-full ${!isDisabled ? "border-2 border-gray-300" : ""}`}
                  disabled={isDisabled}
                >
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {clientFirstPolicyOptions.map((option) => (
                    <SelectItem key={option} value={option} disabled={isDisabled}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* ------- Select 3 ------- */}
            <div>
              <Label className="mb-2">Claim Outcome</Label>
              <Select
                value={formData.claimOutcome}
                onValueChange={(value) => handleChange("claimOutcome", value)}
                disabled={isDisabled}
              >
                <SelectTrigger
                  className={`w-full ${!isDisabled ? "border-2 border-gray-300" : ""}`}
                  disabled={isDisabled}
                >
                  <SelectValue placeholder="Select" />
                </SelectTrigger>
                <SelectContent>
                  {claimOutcomeOption.map((option) => (
                    <SelectItem key={option} value={option} disabled={isDisabled}>
                      {option}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

          </div>

          {/* ---------------- TABLE ---------------- */}
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>#</TableHead>
                  <TableHead>Actions</TableHead>
                  <TableHead>Date of claim</TableHead>
                  <TableHead>Reason for claim</TableHead>
                  <TableHead>Amount of Claim (CA$)</TableHead>
                  <TableHead>Claim Closed On</TableHead>
                  <TableHead>Claim Amount Settled (CA$)</TableHead>
                  <TableHead>Claim Amount Rejected (CA$)</TableHead>
                  <TableHead>Settlement Observations if any</TableHead>
                </TableRow>
              </TableHeader>

              <TableBody>
                {pastClaims.map((claim, index) => (
                  <TableRow key={index}>
                    <TableCell>{index + 1}</TableCell>

                    {/* Delete button */}
                    <TableCell>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => deleteClaimRow(index)}
                        disabled={isDisabled}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </TableCell>

                    {/* Date of Claim Picker */}
                    <TableCell>
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            variant="outline"
                            disabled={isDisabled}
                            className={`w-full justify-start text-left font-normal ${
                              !isDisabled ? "border-2 border-gray-300" : ""
                            }`}
                          >
                            {claim.dateOfClaim
                              ? format(new Date(claim.dateOfClaim), "dd/MM/yyyy")
                              : "DD/MM/YYYY"}
                          </Button>
                        </PopoverTrigger>

                        <PopoverContent className="w-auto p-0">
                          <Calendar
                            mode="single"
                            selected={
                              claim.dateOfClaim ? new Date(claim.dateOfClaim) : undefined
                            }
                            onSelect={(date) => {
                              const updated = [...pastClaims];
                              updated[index].dateOfClaim = date;
                              setPastClaims(updated);
                            }}
                            initialFocus
                            disabled={isDisabled}
                          />
                        </PopoverContent>
                      </Popover>
                    </TableCell>

                    {/* Reason for claim */}
                    <TableCell>
                      <Textarea
                        className={`w-[300px] ${
                          !isDisabled ? "border-2 border-gray-300" : ""
                        }`}
                        value={claim.reasonforClaim}
                        onChange={(e) => {
                          const updated = [...pastClaims];
                          updated[index].reasonforClaim = e.target.value;
                          setPastClaims(updated);
                        }}
                        rows={1}
                        disabled={isDisabled}
                      />
                    </TableCell>

                    {/* Amount of claim */}
                    <TableCell>
                      <Input
                        type="number"
                        value={claim.amountofClaim}
                        onChange={(e) => {
                          const updated = [...pastClaims];
                          updated[index].amountofClaim = e.target.value;
                          setPastClaims(updated);
                        }}
                        disabled={isDisabled}
                        className={!isDisabled ? "border-2 border-gray-300" : ""}
                      />
                    </TableCell>

                    {/* Claim closed on date */}
                    <TableCell>
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            variant="outline"
                            disabled={isDisabled}
                            className={`w-full justify-start text-left font-normal ${
                              !isDisabled ? "border-2 border-gray-300" : ""
                            }`}
                          >
                            {claim.claimClosedOn
                              ? format(new Date(claim.claimClosedOn), "dd/MM/yyyy")
                              : "DD/MM/YYYY"}
                          </Button>
                        </PopoverTrigger>

                        <PopoverContent className="w-auto p-0">
                          <Calendar
                            mode="single"
                            selected={
                              claim.claimClosedOn
                                ? new Date(claim.claimClosedOn)
                                : undefined
                            }
                            onSelect={(date) => {
                              const updated = [...pastClaims];
                              updated[index].claimClosedOn = date;
                              setPastClaims(updated);
                            }}
                            initialFocus
                            disabled={isDisabled}
                          />
                        </PopoverContent>
                      </Popover>
                    </TableCell>

                    {/* Claim Amount Settled */}
                    <TableCell>
                      <Input
                        type="number"
                        value={claim.claimAmountSettled}
                        onChange={(e) => {
                          const updated = [...pastClaims];
                          updated[index].claimAmountSettled = e.target.value;
                          setPastClaims(updated);
                        }}
                        disabled={isDisabled}
                        className={!isDisabled ? "border-2 border-gray-300" : ""}
                      />
                    </TableCell>

                    {/* Claim Amount Rejected */}
                    <TableCell>
                      <Input
                        type="number"
                        value={claim.claimAmountRejected}
                        onChange={(e) => {
                          const updated = [...pastClaims];
                          updated[index].claimAmountRejected = e.target.value;
                          setPastClaims(updated);
                        }}
                        disabled={isDisabled}
                        className={!isDisabled ? "border-2 border-gray-300" : ""}
                      />
                    </TableCell>

                    {/* Settlement Observations */}
                    <TableCell>
                      <Textarea
                        value={claim.settlement}
                        onChange={(e) => {
                          const updated = [...pastClaims];
                          updated[index].settlement = e.target.value;
                          setPastClaims(updated);
                        }}
                        rows={1}
                        className={`w-[300px] ${
                          !isDisabled ? "border-2 border-gray-300" : ""
                        }`}
                        disabled={isDisabled}
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>

            <Button onClick={addRowToClaimTable} className="mt-4" disabled={isDisabled}>
              Add Row
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* -------- Past Claims Section -------- */}
      <Card>
        <CardHeader>
          <CardTitle>Past Claims</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            
            <div>
              <Label className="mb-2">Total Amount Claimed</Label>
              <Input
                type="number"
                value={formData.totalAmountClaimed || ""}
                onChange={(e) => handleChange("totalAmountClaimed", e.target.value)}
                disabled={isDisabled}
                className={!isDisabled ? "border-2 border-gray-300" : ""}
              />
            </div>

            <div>
              <Label className="mb-2">Total Amount Settled</Label>
              <Input
                type="number"
                value={formData.totalAmountSettled || ""}
                onChange={(e) => handleChange("totalAmountSettled", e.target.value)}
                disabled={isDisabled}
                className={!isDisabled ? "border-2 border-gray-300" : ""}
              />
            </div>

            <div>
              <Label className="mb-2">Total Amount Rejected</Label>
              <Input
                type="number"
                value={formData.totalAmountRejected || ""}
                onChange={(e) => handleChange("totalAmountRejected", e.target.value)}
                disabled={isDisabled}
                className={!isDisabled ? "border-2 border-gray-300" : ""}
              />
            </div>

          </div>
        </CardContent>
      </Card>

      {/* -------- SMS Response Section -------- */}
      <Card>
        <CardHeader>
          <CardTitle>SMS Response</CardTitle>
        </CardHeader>
        <CardContent>
          <div>
            <Label className="mb-2">Ringcentral sms response</Label>
            <Textarea
              value={formData.ringcentralSmsResponse || ""}
              onChange={(e) => handleChange("ringcentralSmsResponse", e.target.value)}
              disabled={isDisabled}
              className={!isDisabled ? "border-2 border-gray-300" : ""}
            />
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default Claims;
