// client/app/src/views/Policies/Policy/Components/history.vue
<template>
  <div>
    <h5 class="main-heading mt-2 ps-2">Renewal History</h5>
    <div class="col-lg-4 col-sm-12 mt-2 mb-3 ps-2">
      <label class="my-0">Total Renewal Commissions (CA$</label>
      <div class="">
        <input v-model="formData.totalRenewalCommissions" type="number" disabled
          class="form-control form-control-default" isrequired="false" autocomplete="off" />
      </div>
    </div>
    <div style="width: 100%; overflow: scroll">
      <table class="table border table-responsive subform">
        <thead class="table subform-table-head text-white">
          <tr>
            <th>#</th>
            <th>Actions</th>
            <th>Premium Frequency</th>
            <th>Premium Amount (CA$)</th>
            <th>Policy Amount (CA$)</th>
            <th>Policy Issued Date</th>
            <th>Policy Renewed Date</th>
            <th>Was Medical Required?</th>
            <th>Renewal Commission (CA$)</th>
            <th>Policy Advisor</th>

          </tr>
        </thead>
        <tbody class="table-group-divider">
          <tr v-for="(parent, index) in renewalsHistoryData" :key="index">
            <td class="m-auto">{{ index + 1 }}</td>
            <td>
              <a @click.prevent="deleteLeadsRow(index)" href="javascript:;" data-bs-toggle="tooltip"
                data-bs-original-title="Delete product">
                <i class="fas fa-trash text-secondary" aria-hidden="true"></i>
              </a>
            </td>
            <td>
              <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
                aria-expanded="false">
                <div class="select-box">
                  <select v-model="parent.premiumFrequency" class="multisteps-form__select form-control choices__input"
                    name="choices-state">
                    <option v-for="(option, index) in premiumFrequencyOptions" :key="index" :value="option"
                      :checked="option === '-None-'">{{ option }}</option>

                  </select>
                </div>
              </div>
            </td>
            <td>
              <input v-model="parent.premiumAmount" type="number" class="form-control form-control-default"
                autocomplete="off">
            </td>
            <td>
              <input v-model="parent.policyAmount" type="number" class="form-control form-control-default"
                autocomplete="off">
            </td>
            <td>
              
                <div class="input-group bg-white">
            <flat-pickr v-model="parent.policyIssuedDate" :config="datePickerConfig" placeholder="DD/MM/YYYY"
              class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
              ref="fpDateOfBirth" />
            <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
            </td>
            <td>
             
                <div class="input-group bg-white">
            <flat-pickr v-model="parent.policyRenewalDate" :config="datePickerConfig" placeholder="DD/MM/YYYY"
              class="form-control form-control-default" :required="false" autocomplete="off" id="dateOfBirth"
              ref="fpDateOfBirth" />
            <span class="input-group-text" @click="$refs.fpDateOfBirth.fp.open()">
              <i class="fa fa-calendar"></i>
            </span>
          </div>
            </td>
            <td>
              <div class="choices" data-type="select-one" tabindex="0" role="listbox" aria-haspopup="true"
                aria-expanded="false">
                <div class="select-box">
                  <select v-model="parent.medicalRequired" class="multisteps-form__select form-control choices__input"
                    name="choices-state">
                    <option v-for="(option, index) in clientFirstPolicyOptions" :key="index" :value="option"
                      :checked="option === '-None-'">{{ option }}</option>


                  </select>
                </div>
              </div>
            </td>
            <td>
              <input v-model="parent.renewalCommission" type="text" class="form-control form-control-default"
                autocomplete="off">
            </td>

            <td>
              <textarea v-model="parent.PolicyAdvisor" class="form-control form-control-default" rows="1"></textarea>
            </td>


          </tr>
        </tbody>
      </table>
    </div>
    <button class="btn mb-0 btn-color btn-md" type="button" @click.prevent="addRowToRenewalHistoryTable">
      Add Row
    </button>
  </div>
  <div class="button-row d-flex justify-content-center mt-4 gap-4">
    <button class="btn mb-0 bg-gradient-light btn-md null null js-btn-prev" type="button" @click="prevStep">
      Prev
    </button>

    <button class="btn mb-0 bg-gradient-dark btn-md null null js-btn-next" type="button" @click.prevent="nextStep">
      Submit
    </button>
  </div>
</template>
<script>
import { premiumFrequencyOptions, clientFirstPolicyOptions } from "../../utils/picklist.js";
import flatPickr from 'vue-flatpickr-component';
import 'flatpickr/dist/flatpickr.css';
export default {
  components: { flatPickr },
  props: {
    History: {
      type: Object,
      required: true
    }
  },
  watch: {
    History: {
      handler() {
        this.formData = { ...this.History };
        this.renewalsHistoryData = this.History?.renewalsHistoryData || [];
      },
      immediate: true,
      deep: true
    }
  },
  data() {
    return {
      datePickerConfig: {
        dateFormat: "d/m/Y", // DD/MM/YYYY
        allowInput: true
      },
      dateTimePickerConfig: {
        dateFormat: "d/m/Y H:i", // DD/MM/YYYY HH:mm
        allowInput: true,
        enableTime: true,
        time_24hr: true
      },
      formData: { ...this.History },
      renewalsHistoryData: [],
      clientFirstPolicyOptions: { ...clientFirstPolicyOptions },
      premiumFrequencyOptions: { ...premiumFrequencyOptions },
    };
  },
  methods: {
    openDatePicker() {
      if (this.$refs.fpDateOfBirth && this.$refs.fpDateOfBirth.fp) {
        this.$refs.fpDateOfBirth.fp.open()
      }
      },
      addRowToRenewalHistoryTable() {
        this.renewalsHistoryData.push({
          premiumFrequency: "",
          premiumAmount: "",
          policyAmount: "",
          policyIssuedDate: "",
          policyRenewalDate: "",
          medicalRequired: "",
          renewalCommission: "",
          PolicyAdvisor: ""
        });
      },
      deleteLeadsRow(index) {
        this.renewalsHistoryData.splice(index, 1);
      },
      nextStep() {
        this.$emit('next', { ...this.formData, renewalsHistoryData: this.renewalsHistoryData });
      },
      prevStep() {
        this.$emit('previous');
      }

    }
  };
</script>

<style scoped>
.main-heading {
  font-weight: 500 !important;
}

.form-control-default {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 0.5rem;
  width: 100%;
}

.my-0 {
  margin-bottom: 0 !important;
}
</style>

// frontend/src/features/Policy/policyFormComponents/History.jsx
import React, { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { format } from "date-fns";
import { Trash2 } from "lucide-react";

const History = ({ formData, setFormData, onNext, onPrev, isDisabled }) => {
  const [renewalsHistoryData, setRenewalsHistoryData] = useState(formData.renewalsHistoryData || []);

  const handleChange = (field, value) => {
    setFormData({ ...formData, [field]: value });
  };

  const addRowToRenewalHistoryTable = () => {
    setRenewalsHistoryData([...renewalsHistoryData, {
      premiumFrequency: "",
      premiumAmount: "",
      policyAmount: "",
      policyIssuedDate: "",
      policyRenewalDate: "",
      medicalRequired: "",
      renewalCommission: "",
      PolicyAdvisor: ""
    }]);
  };

  const deleteLeadsRow = (index) => {
    setRenewalsHistoryData(renewalsHistoryData.filter((_, i) => i !== index));
  };

  const handleNext = () => {
    setFormData({ ...formData, renewalsHistoryData });
    onNext();
  };

  // Mock options - replace with actual data
  const premiumFrequencyOptions = ["Monthly", "Yearly", "Quarterly"];
  const clientFirstPolicyOptions = ["Yes", "No", "-None-"];

  return (
   <div className="space-y-6">
  <Card>
    <CardHeader>
      <CardTitle>Renewal History</CardTitle>
    </CardHeader>
    <CardContent className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div>
          <Label className="mb-2">Total Renewal Commissions (CA$)</Label>
          <Input
            type="number"
            value={formData.totalRenewalCommissions || ""}
            onChange={(e) => handleChange("totalRenewalCommissions", e.target.value)}
            disabled={isDisabled}
            className={!isDisabled ? "border-2 border-gray-300" : ""}
          />
        </div>
      </div>

      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>#</TableHead>
              <TableHead>Actions</TableHead>
              <TableHead>Premium Frequency</TableHead>
              <TableHead>Premium Amount (CA$)</TableHead>
              <TableHead>Policy Amount (CA$)</TableHead>
              <TableHead>Policy Issued Date</TableHead>
              <TableHead>Policy Renewed Date</TableHead>
              <TableHead>Was Medical Required?</TableHead>
              <TableHead>Renewal Commission (CA$)</TableHead>
              <TableHead>Policy Advisor</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {renewalsHistoryData.map((renewal, index) => (
              <TableRow key={index}>
                <TableCell>{index + 1}</TableCell>
                <TableCell>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => deleteLeadsRow(index)}
                    disabled={isDisabled}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </TableCell>
                <TableCell>
                  <Select
                    value={renewal.premiumFrequency}
                    onValueChange={(value) => {
                      const updated = [...renewalsHistoryData];
                      updated[index].premiumFrequency = value;
                      setRenewalsHistoryData(updated);
                    }}
                    disabled={isDisabled}
                  >
                    <SelectTrigger className={`w-full ${!isDisabled ? "border-2 border-gray-300" : ""}`}>
                      <SelectValue placeholder="Select" />
                    </SelectTrigger>
                    <SelectContent>
                      {premiumFrequencyOptions.map((option) => (
                        <SelectItem key={option} value={option}>{option}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <Input
                    type="number"
                    value={renewal.premiumAmount}
                    onChange={(e) => {
                      const updated = [...renewalsHistoryData];
                      updated[index].premiumAmount = e.target.value;
                      setRenewalsHistoryData(updated);
                    }}
                    disabled={isDisabled}
                    className={!isDisabled ? "border-2 border-gray-300" : ""}
                  />
                </TableCell>
                <TableCell>
                  <Input
                    type="number"
                    value={renewal.policyAmount}
                    onChange={(e) => {
                      const updated = [...renewalsHistoryData];
                      updated[index].policyAmount = e.target.value;
                      setRenewalsHistoryData(updated);
                    }}
                    disabled={isDisabled}
                    className={!isDisabled ? "border-2 border-gray-300" : ""}
                  />
                </TableCell>
                <TableCell>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={`w-full justify-start text-left font-normal ${!isDisabled ? "border-2 border-gray-300" : ""}`}
                        disabled={isDisabled}
                      >
                        {renewal.policyIssuedDate ? format(new Date(renewal.policyIssuedDate), "dd/MM/yyyy") : "DD/MM/YYYY"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={renewal.policyIssuedDate ? new Date(renewal.policyIssuedDate) : undefined}
                        onSelect={(date) => {
                          const updated = [...renewalsHistoryData];
                          updated[index].policyIssuedDate = date;
                          setRenewalsHistoryData(updated);
                        }}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </TableCell>
                <TableCell>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className={`w-full justify-start text-left font-normal ${!isDisabled ? "border-2 border-gray-300" : ""}`}
                        disabled={isDisabled}
                      >
                        {renewal.policyRenewalDate ? format(new Date(renewal.policyRenewalDate), "dd/MM/yyyy") : "DD/MM/YYYY"}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0">
                      <Calendar
                        mode="single"
                        selected={renewal.policyRenewalDate ? new Date(renewal.policyRenewalDate) : undefined}
                        onSelect={(date) => {
                          const updated = [...renewalsHistoryData];
                          updated[index].policyRenewalDate = date;
                          setRenewalsHistoryData(updated);
                        }}
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </TableCell>
                <TableCell>
                  <Select
                    value={renewal.medicalRequired}
                    onValueChange={(value) => {
                      const updated = [...renewalsHistoryData];
                      updated[index].medicalRequired = value;
                      setRenewalsHistoryData(updated);
                    }}
                    disabled={isDisabled}
                  >
                    <SelectTrigger className={`w-full ${!isDisabled ? "border-2 border-gray-300" : ""}`}>
                      <SelectValue placeholder="Select" />
                    </SelectTrigger>
                    <SelectContent>
                      {clientFirstPolicyOptions.map((option) => (
                        <SelectItem key={option} value={option}>{option}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell>
                  <Input
                    value={renewal.renewalCommission}
                    onChange={(e) => {
                      const updated = [...renewalsHistoryData];
                      updated[index].renewalCommission = e.target.value;
                      setRenewalsHistoryData(updated);
                    }}
                    disabled={isDisabled}
                    className={!isDisabled ? "border-2 border-gray-300" : ""}
                  />
                </TableCell>
                <TableCell>
                  <Textarea
                    value={renewal.PolicyAdvisor}
                    onChange={(e) => {
                      const updated = [...renewalsHistoryData];
                      updated[index].PolicyAdvisor = e.target.value;
                      setRenewalsHistoryData(updated);
                    }}
                    rows={1}
                    disabled={isDisabled}
                    className={`w-[300px] ${!isDisabled ? "border-2 border-gray-300" : ""}`}
                  />
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        <Button onClick={addRowToRenewalHistoryTable} className="mt-4" disabled={isDisabled}>
          Add Row
        </Button>
      </div>
    </CardContent>
  </Card>
</div>

  );
};

export default History;
